// Terraform file generators for IBM Cloud, Oracle OCI, Alibaba Cloud, DigitalOcean, Linode.
// Each cloud returns Record<filename, content> matching the same shape as terraform-generator.ts.

export type AltTfCloud = "ibm" | "oci" | "alibaba" | "do" | "linode";

const DATE = new Date().toISOString().slice(0, 10);

// ── helpers ──────────────────────────────────────────────────────────────────

const banner = (cloud: string, file: string, desc: string) =>
  `# ${"═".repeat(60)}\n# ${file} — ${cloud} | ${desc}\n# Generated by InfraStudio · ${DATE}\n# ${"═".repeat(60)}\n`;

const has = (services: string[], ...ids: string[]) => ids.some(id => services.includes(id));

// ── IBM Cloud ─────────────────────────────────────────────────────────────────

function ibmFiles(services: string[], region: string): Record<string, string> {
  const files: Record<string, string> = {};

  files["main.tf"] = banner("IBM Cloud", "main.tf", "Provider & Terraform settings") + `
terraform {
  required_version = ">= 1.5"
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = "~> 1.65"
    }
  }
}

provider "ibm" {
  region = var.ibm_region
}

# HOW TO USE:
#   export IC_API_KEY="<your-ibm-cloud-api-key>"
#   terraform init
#   terraform plan  -var-file="dev.tfvars"
#   terraform apply -var-file="dev.tfvars"
#
# Docs: https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs`;

  files["variables.tf"] = banner("IBM Cloud", "variables.tf", "Input variables") + `
variable "project_name"       { type = string; default = "myapp" }
variable "environment"        { type = string; default = "dev" }
variable "ibm_region"         { type = string; default = "${region}" }
variable "node_count"         { type = number; default = 2 }
variable "machine_type"       { type = string; default = "bx2.4x16"  }
variable "db_plan"            { type = string; default = "standard"   }
variable "storage_class"      { type = string; default = "standard"   }
variable "enable_monitoring"  { type = bool;   default = false        }
variable "log_retention_days" { type = number; default = 7            }
variable "multi_az"           { type = bool;   default = false        }`;

  files["networking.tf"] = banner("IBM Cloud", "networking.tf", "VPC, subnets, security groups") + `
resource "ibm_resource_group" "main" {
  name = "\${var.project_name}-\${var.environment}"
}

resource "ibm_is_vpc" "main" {
  name           = "\${var.project_name}-vpc-\${var.environment}"
  resource_group = ibm_resource_group.main.id
  tags           = [var.project_name, var.environment]
}

resource "ibm_is_public_gateway" "main" {
  name           = "\${var.project_name}-pgw-\${var.environment}"
  vpc            = ibm_is_vpc.main.id
  zone           = "\${var.ibm_region}-1"
  resource_group = ibm_resource_group.main.id
}

resource "ibm_is_subnet" "public" {
  name                     = "\${var.project_name}-public-\${var.environment}"
  vpc                      = ibm_is_vpc.main.id
  zone                     = "\${var.ibm_region}-1"
  total_ipv4_address_count = 256
  public_gateway           = ibm_is_public_gateway.main.id
  resource_group           = ibm_resource_group.main.id
}

resource "ibm_is_subnet" "private" {
  name                     = "\${var.project_name}-private-\${var.environment}"
  vpc                      = ibm_is_vpc.main.id
  zone                     = "\${var.ibm_region}-2"
  total_ipv4_address_count = 256
  resource_group           = ibm_resource_group.main.id
}

resource "ibm_is_security_group" "app" {
  name           = "\${var.project_name}-sg-\${var.environment}"
  vpc            = ibm_is_vpc.main.id
  resource_group = ibm_resource_group.main.id
}

resource "ibm_is_security_group_rule" "https_in" {
  group     = ibm_is_security_group.app.id
  direction = "inbound"
  remote    = "0.0.0.0/0"
  tcp { port_min = 443; port_max = 443 }
}`;

  if (has(services, "control-plane", "vm-instance", "serverless-compute")) {
    files["compute.tf"] = banner("IBM Cloud", "compute.tf", "IKS Kubernetes cluster") + `
resource "ibm_container_vpc_cluster" "main" {
  name              = "\${var.project_name}-iks-\${var.environment}"
  vpc_id            = ibm_is_vpc.main.id
  flavor            = var.machine_type
  worker_count      = var.node_count
  kube_version      = "1.29"
  resource_group_id = ibm_resource_group.main.id
  wait_till         = "IngressReady"

  zones {
    subnet_id = ibm_is_subnet.private.id
    name      = "\${var.ibm_region}-1"
  }

  tags = [var.project_name, var.environment]
}

data "ibm_container_cluster_config" "main" {
  cluster_name_id   = ibm_container_vpc_cluster.main.id
  resource_group_id = ibm_resource_group.main.id
}`;
  }

  if (has(services, "managed-database", "database")) {
    files["database.tf"] = banner("IBM Cloud", "database.tf", "IBM Databases for PostgreSQL") + `
resource "ibm_database" "main" {
  name              = "\${var.project_name}-db-\${var.environment}"
  plan              = var.db_plan
  location          = var.ibm_region
  service           = "databases-for-postgresql"
  resource_group_id = ibm_resource_group.main.id
  tags              = [var.project_name, var.environment]

  parameters_json = jsonencode({
    members_memory_allocation_mb = 2048
    members_disk_allocation_mb   = 20480
  })

  timeouts { create = "120m"; update = "60m"; delete = "15m" }
}

resource "ibm_resource_key" "db_key" {
  name                 = "\${var.project_name}-db-key-\${var.environment}"
  role                 = "Administrator"
  resource_instance_id = ibm_database.main.id
}`;
  }

  if (has(services, "block-storage", "object-storage", "file-storage")) {
    files["storage.tf"] = banner("IBM Cloud", "storage.tf", "Cloud Object Storage (COS)") + `
resource "ibm_resource_instance" "cos" {
  name              = "\${var.project_name}-cos-\${var.environment}"
  service           = "cloud-object-storage"
  plan              = "standard"
  location          = "global"
  resource_group_id = ibm_resource_group.main.id
  tags              = [var.project_name, var.environment]
}

resource "ibm_cos_bucket" "main" {
  bucket_name          = "\${var.project_name}-\${var.environment}-data"
  resource_instance_id = ibm_resource_instance.cos.id
  region_location      = var.ibm_region
  storage_class        = var.storage_class
}`;
  }

  if (has(services, "load-balancer")) {
    files["loadbalancer.tf"] = banner("IBM Cloud", "loadbalancer.tf", "Application Load Balancer") + `
resource "ibm_is_lb" "main" {
  name           = "\${var.project_name}-lb-\${var.environment}"
  subnets        = [ibm_is_subnet.public.id]
  type           = "public"
  resource_group = ibm_resource_group.main.id
  tags           = [var.project_name, var.environment]
}

resource "ibm_is_lb_listener" "https" {
  lb           = ibm_is_lb.main.id
  port         = 443
  protocol     = "https"
  default_pool = ibm_is_lb_pool.main.id
}

resource "ibm_is_lb_pool" "main" {
  lb                  = ibm_is_lb.main.id
  name                = "app-pool"
  protocol            = "http"
  algorithm           = "round_robin"
  health_delay        = 10
  health_retries      = 2
  health_timeout      = 5
  health_type         = "http"
  health_monitor_url  = "/health"
  health_monitor_port = 8080
}`;
  }

  files["outputs.tf"] = banner("IBM Cloud", "outputs.tf", "Resource identifiers & connection info") + `
output "resource_group_id" { value = ibm_resource_group.main.id }
output "vpc_id"             { value = ibm_is_vpc.main.id }
output "public_subnet_id"  { value = ibm_is_subnet.public.id }
output "private_subnet_id" { value = ibm_is_subnet.private.id }` +
    (has(services, "control-plane", "vm-instance") ? `
output "cluster_id"   { value = ibm_container_vpc_cluster.main.id }
output "cluster_name" { value = ibm_container_vpc_cluster.main.name }` : "") +
    (has(services, "managed-database", "database") ? `
output "db_id" { value = ibm_database.main.id; sensitive = true }` : "") +
    (has(services, "block-storage", "object-storage", "file-storage") ? `
output "cos_bucket" { value = ibm_cos_bucket.main.bucket_name }` : "");

  return files;
}

// ── Oracle Cloud (OCI) ────────────────────────────────────────────────────────

function ociFiles(services: string[], region: string): Record<string, string> {
  const files: Record<string, string> = {};

  files["main.tf"] = banner("Oracle Cloud (OCI)", "main.tf", "Provider & Terraform settings") + `
terraform {
  required_version = ">= 1.5"
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 5.20"
    }
  }
}

provider "oci" {
  region = var.oci_region
  # Credentials read from env or ~/.oci/config:
  # OCI_TENANCY_OCID, OCI_USER_OCID, OCI_FINGERPRINT, OCI_PRIVATE_KEY_PATH
}

# HOW TO USE:
#   export OCI_TENANCY_OCID="ocid1.tenancy.oc1..<unique_id>"
#   export OCI_USER_OCID="ocid1.user.oc1..<unique_id>"
#   export OCI_FINGERPRINT="<key-fingerprint>"
#   export OCI_PRIVATE_KEY_PATH="~/.oci/oci_api_key.pem"
#   terraform init
#   terraform apply -var-file="dev.tfvars"
#
# Docs: https://registry.terraform.io/providers/oracle/oci/latest/docs`;

  files["variables.tf"] = banner("Oracle Cloud (OCI)", "variables.tf", "Input variables") + `
variable "project_name"       { type = string; default = "myapp"           }
variable "environment"        { type = string; default = "dev"             }
variable "oci_region"         { type = string; default = "${region}"        }
variable "compartment_ocid"   { type = string; description = "Target OCI compartment OCID" }
variable "node_count"         { type = number; default = 2                 }
variable "node_shape"         { type = string; default = "VM.Standard.E4.Flex" }
variable "node_ocpus"         { type = number; default = 2                 }
variable "node_memory_gb"     { type = number; default = 16                }
variable "db_shape"           { type = string; default = "VM.Standard.E4.Flex" }
variable "storage_size_gb"    { type = number; default = 50                }
variable "enable_monitoring"  { type = bool;   default = false             }
variable "log_retention_days" { type = number; default = 7                 }`;

  files["networking.tf"] = banner("Oracle Cloud (OCI)", "networking.tf", "VCN, subnets, security lists") + `
resource "oci_core_vcn" "main" {
  compartment_id = var.compartment_ocid
  cidr_blocks    = ["10.0.0.0/16"]
  display_name   = "\${var.project_name}-vcn-\${var.environment}"
  dns_label      = "\${var.project_name}\${var.environment}"

  freeform_tags = { "project" = var.project_name, "env" = var.environment }
}

resource "oci_core_internet_gateway" "main" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.main.id
  display_name   = "\${var.project_name}-igw-\${var.environment}"
  enabled        = true
}

resource "oci_core_nat_gateway" "main" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.main.id
  display_name   = "\${var.project_name}-nat-\${var.environment}"
}

resource "oci_core_route_table" "public" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.main.id
  display_name   = "\${var.project_name}-rt-public-\${var.environment}"

  route_rules {
    network_entity_id = oci_core_internet_gateway.main.id
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
  }
}

resource "oci_core_route_table" "private" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.main.id
  display_name   = "\${var.project_name}-rt-private-\${var.environment}"

  route_rules {
    network_entity_id = oci_core_nat_gateway.main.id
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
  }
}

resource "oci_core_subnet" "public" {
  compartment_id    = var.compartment_ocid
  vcn_id            = oci_core_vcn.main.id
  cidr_block        = "10.0.1.0/24"
  display_name      = "\${var.project_name}-subnet-public-\${var.environment}"
  dns_label         = "public"
  route_table_id    = oci_core_route_table.public.id
  prohibit_public_ip_on_vnic = false
}

resource "oci_core_subnet" "private" {
  compartment_id    = var.compartment_ocid
  vcn_id            = oci_core_vcn.main.id
  cidr_block        = "10.0.2.0/24"
  display_name      = "\${var.project_name}-subnet-private-\${var.environment}"
  dns_label         = "private"
  route_table_id    = oci_core_route_table.private.id
  prohibit_public_ip_on_vnic = true
}

resource "oci_core_security_list" "app" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.main.id
  display_name   = "\${var.project_name}-sl-app-\${var.environment}"

  egress_security_rules {
    protocol    = "all"
    destination = "0.0.0.0/0"
  }

  ingress_security_rules {
    protocol = "6"
    source   = "0.0.0.0/0"
    tcp_options { min = 443; max = 443 }
  }
}`;

  if (has(services, "control-plane", "vm-instance")) {
    files["compute.tf"] = banner("Oracle Cloud (OCI)", "compute.tf", "OKE Kubernetes cluster") + `
resource "oci_containerengine_cluster" "main" {
  compartment_id     = var.compartment_ocid
  kubernetes_version = "v1.29.1"
  name               = "\${var.project_name}-oke-\${var.environment}"
  vcn_id             = oci_core_vcn.main.id

  endpoint_config {
    is_public_ip_enabled = false
    subnet_id            = oci_core_subnet.public.id
  }

  options {
    service_lb_subnet_ids = [oci_core_subnet.public.id]
    add_ons {
      is_kubernetes_dashboard_enabled = false
      is_tiller_enabled               = false
    }
  }

  freeform_tags = { "project" = var.project_name, "env" = var.environment }
}

resource "oci_containerengine_node_pool" "main" {
  cluster_id         = oci_containerengine_cluster.main.id
  compartment_id     = var.compartment_ocid
  kubernetes_version = "v1.29.1"
  name               = "\${var.project_name}-nodepool-\${var.environment}"

  node_shape = var.node_shape

  node_shape_config {
    ocpus         = var.node_ocpus
    memory_in_gbs = var.node_memory_gb
  }

  node_config_details {
    size = var.node_count

    placement_configs {
      availability_domain = "\${var.oci_region}-1"
      subnet_id           = oci_core_subnet.private.id
    }
  }

  node_source_details {
    image_id    = data.oci_core_images.worker.images[0].id
    source_type = "IMAGE"
  }
}

data "oci_core_images" "worker" {
  compartment_id           = var.compartment_ocid
  operating_system         = "Oracle Linux"
  operating_system_version = "8"
  shape                    = var.node_shape
  sort_by                  = "TIMECREATED"
  sort_order               = "DESC"
}`;
  }

  if (has(services, "managed-database", "database")) {
    files["database.tf"] = banner("Oracle Cloud (OCI)", "database.tf", "Autonomous Database (ADB)") + `
resource "oci_database_autonomous_database" "main" {
  compartment_id           = var.compartment_ocid
  db_name                  = "\${var.project_name}\${var.environment}db"
  display_name             = "\${var.project_name}-adb-\${var.environment}"
  db_workload              = "OLTP"
  is_free_tier             = var.environment == "dev" ? true : false
  cpu_core_count           = var.environment == "prod" ? 4 : 1
  data_storage_size_in_tbs = 1
  is_auto_scaling_enabled  = var.environment == "prod"
  admin_password           = random_password.db_admin.result

  freeform_tags = { "project" = var.project_name, "env" = var.environment }
}

resource "random_password" "db_admin" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}`;
  }

  if (has(services, "block-storage", "object-storage", "file-storage")) {
    files["storage.tf"] = banner("Oracle Cloud (OCI)", "storage.tf", "Object Storage namespace & bucket") + `
data "oci_objectstorage_namespace" "main" {
  compartment_id = var.compartment_ocid
}

resource "oci_objectstorage_bucket" "main" {
  compartment_id = var.compartment_ocid
  namespace      = data.oci_objectstorage_namespace.main.namespace
  name           = "\${var.project_name}-\${var.environment}-data"
  access_type    = "NoPublicAccess"
  storage_tier   = "Standard"

  freeform_tags = { "project" = var.project_name, "env" = var.environment }
}

resource "oci_objectstorage_object_lifecycle_policy" "main" {
  bucket    = oci_objectstorage_bucket.main.name
  namespace = data.oci_objectstorage_namespace.main.namespace

  rules {
    action      = "ARCHIVE"
    is_enabled  = true
    name        = "archive-old-objects"
    time_amount = 90
    time_unit   = "DAYS"
  }
}`;
  }

  if (has(services, "load-balancer")) {
    files["loadbalancer.tf"] = banner("Oracle Cloud (OCI)", "loadbalancer.tf", "OCI Load Balancer") + `
resource "oci_load_balancer_load_balancer" "main" {
  compartment_id = var.compartment_ocid
  display_name   = "\${var.project_name}-lb-\${var.environment}"
  shape          = "flexible"
  subnet_ids     = [oci_core_subnet.public.id]
  is_private     = false

  shape_details {
    minimum_bandwidth_in_mbps = 10
    maximum_bandwidth_in_mbps = 100
  }

  freeform_tags = { "project" = var.project_name, "env" = var.environment }
}

resource "oci_load_balancer_backend_set" "main" {
  load_balancer_id = oci_load_balancer_load_balancer.main.id
  name             = "app-backend-set"
  policy           = "ROUND_ROBIN"

  health_checker {
    protocol          = "HTTP"
    port              = 8080
    url_path          = "/health"
    return_code       = 200
    interval_ms       = 10000
    timeout_in_millis = 3000
    retries           = 3
  }
}`;
  }

  files["outputs.tf"] = banner("Oracle Cloud (OCI)", "outputs.tf", "Resource identifiers") + `
output "vcn_id"             { value = oci_core_vcn.main.id }
output "public_subnet_id"  { value = oci_core_subnet.public.id }
output "private_subnet_id" { value = oci_core_subnet.private.id }` +
    (has(services, "control-plane", "vm-instance") ? `
output "cluster_id"   { value = oci_containerengine_cluster.main.id }` : "") +
    (has(services, "managed-database", "database") ? `
output "adb_id"            { value = oci_database_autonomous_database.main.id }
output "adb_service_url"   { value = oci_database_autonomous_database.main.service_console_url }` : "") +
    (has(services, "block-storage", "object-storage", "file-storage") ? `
output "bucket_name" { value = oci_objectstorage_bucket.main.name }` : "");

  return files;
}

// ── Alibaba Cloud ─────────────────────────────────────────────────────────────

function alibabaFiles(services: string[], region: string): Record<string, string> {
  const files: Record<string, string> = {};

  files["main.tf"] = banner("Alibaba Cloud", "main.tf", "Provider & Terraform settings") + `
terraform {
  required_version = ">= 1.5"
  required_providers {
    alicloud = {
      source  = "aliyun/alicloud"
      version = "~> 1.220"
    }
  }
}

provider "alicloud" {
  region = var.alicloud_region
  # Credentials: set ALICLOUD_ACCESS_KEY and ALICLOUD_SECRET_KEY env vars
}

# HOW TO USE:
#   export ALICLOUD_ACCESS_KEY="<your-access-key-id>"
#   export ALICLOUD_SECRET_KEY="<your-access-key-secret>"
#   terraform init
#   terraform apply -var-file="dev.tfvars"
#
# Docs: https://registry.terraform.io/providers/aliyun/alicloud/latest/docs`;

  files["variables.tf"] = banner("Alibaba Cloud", "variables.tf", "Input variables") + `
variable "project_name"       { type = string; default = "myapp"            }
variable "environment"        { type = string; default = "dev"              }
variable "alicloud_region"    { type = string; default = "${region}"         }
variable "node_count"         { type = number; default = 2                  }
variable "instance_type"      { type = string; default = "ecs.c6.large"     }
variable "db_instance_class"  { type = string; default = "rds.mysql.s1.small" }
variable "storage_size_gb"    { type = number; default = 50                 }
variable "enable_monitoring"  { type = bool;   default = false              }
variable "log_retention_days" { type = number; default = 7                  }
variable "k8s_version"        { type = string; default = "1.29.1-aliyun.1"  }`;

  files["networking.tf"] = banner("Alibaba Cloud", "networking.tf", "VPC, vSwitches, security groups") + `
resource "alicloud_vpc" "main" {
  vpc_name   = "\${var.project_name}-vpc-\${var.environment}"
  cidr_block = "10.0.0.0/16"
  tags = { Project = var.project_name, Env = var.environment }
}

data "alicloud_zones" "main" {
  available_instance_type = var.instance_type
}

resource "alicloud_vswitch" "public" {
  vpc_id       = alicloud_vpc.main.id
  cidr_block   = "10.0.1.0/24"
  zone_id      = data.alicloud_zones.main.zones[0].id
  vswitch_name = "\${var.project_name}-vsw-public-\${var.environment}"
  tags         = { Project = var.project_name, Env = var.environment }
}

resource "alicloud_vswitch" "private" {
  vpc_id       = alicloud_vpc.main.id
  cidr_block   = "10.0.2.0/24"
  zone_id      = data.alicloud_zones.main.zones[0].id
  vswitch_name = "\${var.project_name}-vsw-private-\${var.environment}"
  tags         = { Project = var.project_name, Env = var.environment }
}

resource "alicloud_security_group" "app" {
  name   = "\${var.project_name}-sg-\${var.environment}"
  vpc_id = alicloud_vpc.main.id
  tags   = { Project = var.project_name, Env = var.environment }
}

resource "alicloud_security_group_rule" "https_in" {
  type              = "ingress"
  ip_protocol       = "tcp"
  policy            = "accept"
  port_range        = "443/443"
  security_group_id = alicloud_security_group.app.id
  cidr_ip           = "0.0.0.0/0"
}

resource "alicloud_nat_gateway" "main" {
  vpc_id               = alicloud_vpc.main.id
  nat_gateway_name     = "\${var.project_name}-nat-\${var.environment}"
  payment_type         = "PayAsYouGo"
  vswitch_id           = alicloud_vswitch.public.id
  nat_type             = "Enhanced"
}`;

  if (has(services, "control-plane", "vm-instance")) {
    files["compute.tf"] = banner("Alibaba Cloud", "compute.tf", "ACK Kubernetes cluster") + `
resource "alicloud_cs_managed_kubernetes" "main" {
  name                 = "\${var.project_name}-ack-\${var.environment}"
  cluster_spec         = "ack.pro.small"
  version              = var.k8s_version
  vpc_id               = alicloud_vpc.main.id
  pod_cidr             = "172.20.0.0/16"
  service_cidr         = "172.21.0.0/20"
  new_nat_gateway      = false
  slb_internet_enabled = true

  worker_vswitch_ids = [alicloud_vswitch.private.id]

  tags = { Project = var.project_name, Env = var.environment }
}

resource "alicloud_cs_kubernetes_node_pool" "main" {
  cluster_id     = alicloud_cs_managed_kubernetes.main.id
  name           = "\${var.project_name}-pool-\${var.environment}"
  vswitch_ids    = [alicloud_vswitch.private.id]
  instance_types = [var.instance_type]
  desired_size   = var.node_count
  system_disk_category = "cloud_efficiency"
  system_disk_size     = 60

  tags = { Project = var.project_name, Env = var.environment }
}`;
  }

  if (has(services, "serverless-compute")) {
    files["serverless.tf"] = banner("Alibaba Cloud", "serverless.tf", "Alibaba Function Compute") + `
resource "alicloud_fc_service" "main" {
  name        = "\${var.project_name}-fc-\${var.environment}"
  description = "Function Compute service for \${var.project_name}"
  vpc_config {
    vpc_id     = alicloud_vpc.main.id
    vswitch_ids = [alicloud_vswitch.private.id]
    security_group_id = alicloud_security_group.app.id
  }
}

resource "alicloud_fc_function" "main" {
  service     = alicloud_fc_service.main.name
  name        = "\${var.project_name}-fn-\${var.environment}"
  handler     = "index.handler"
  runtime     = "nodejs16"
  memory_size = 512
  timeout     = 60
}`;
  }

  if (has(services, "managed-database", "database")) {
    files["database.tf"] = banner("Alibaba Cloud", "database.tf", "ApsaraDB RDS for MySQL") + `
resource "alicloud_db_instance" "main" {
  engine               = "MySQL"
  engine_version       = "8.0"
  instance_type        = var.db_instance_class
  instance_storage     = var.storage_size_gb
  instance_name        = "\${var.project_name}-rds-\${var.environment}"
  vswitch_id           = alicloud_vswitch.private.id
  security_group_ids   = [alicloud_security_group.app.id]
  db_instance_ip_array_name = "default"
  tags = { Project = var.project_name, Env = var.environment }
}

resource "alicloud_db_database" "main" {
  instance_id   = alicloud_db_instance.main.id
  name          = var.project_name
  character_set = "utf8mb4"
}

resource "alicloud_db_account" "main" {
  db_instance_id   = alicloud_db_instance.main.id
  account_name     = "appuser"
  account_password = random_password.db.result
  account_type     = "Normal"
}

resource "random_password" "db" {
  length  = 16
  special = false
}`;
  }

  if (has(services, "block-storage", "object-storage", "file-storage")) {
    files["storage.tf"] = banner("Alibaba Cloud", "storage.tf", "OSS (Object Storage Service)") + `
resource "alicloud_oss_bucket" "main" {
  bucket = "\${var.project_name}-\${var.environment}-data"
  acl    = "private"

  lifecycle_rule {
    id      = "archive-old"
    enabled = true
    prefix  = "archive/"

    transition {
      days          = 60
      storage_class = "IA"
    }
    expiration {
      days = 365
    }
  }

  tags = { Project = var.project_name, Env = var.environment }
}`;
  }

  if (has(services, "load-balancer")) {
    files["loadbalancer.tf"] = banner("Alibaba Cloud", "loadbalancer.tf", "Application Load Balancer (ALB)") + `
resource "alicloud_alb_load_balancer" "main" {
  load_balancer_name    = "\${var.project_name}-alb-\${var.environment}"
  load_balancer_edition = "Standard"
  vpc_id                = alicloud_vpc.main.id
  address_type          = "Internet"
  address_allocated_mode = "Fixed"

  zone_mappings {
    zone_id    = data.alicloud_zones.main.zones[0].id
    vswitch_id = alicloud_vswitch.public.id
  }

  tags = { Project = var.project_name, Env = var.environment }
}`;
  }

  files["outputs.tf"] = banner("Alibaba Cloud", "outputs.tf", "Resource identifiers") + `
output "vpc_id"            { value = alicloud_vpc.main.id }
output "public_vswitch_id" { value = alicloud_vswitch.public.id }
output "private_vswitch_id"{ value = alicloud_vswitch.private.id }` +
    (has(services, "control-plane", "vm-instance") ? `
output "cluster_id"   { value = alicloud_cs_managed_kubernetes.main.id }` : "") +
    (has(services, "managed-database", "database") ? `
output "rds_connection_string" { value = alicloud_db_instance.main.connection_string }` : "") +
    (has(services, "block-storage", "object-storage", "file-storage") ? `
output "oss_bucket" { value = alicloud_oss_bucket.main.bucket }` : "");

  return files;
}

// ── DigitalOcean ──────────────────────────────────────────────────────────────

function doFiles(services: string[], region: string): Record<string, string> {
  const files: Record<string, string> = {};

  files["main.tf"] = banner("DigitalOcean", "main.tf", "Provider & Terraform settings") + `
terraform {
  required_version = ">= 1.5"
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.36"
    }
  }
}

provider "digitalocean" {
  token = var.do_token
}

# HOW TO USE:
#   export DIGITALOCEAN_TOKEN="<your-personal-access-token>"
#   terraform init
#   terraform apply -var-file="dev.tfvars"
#
# Docs: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs`;

  files["variables.tf"] = banner("DigitalOcean", "variables.tf", "Input variables") + `
variable "project_name"       { type = string; default = "myapp"        }
variable "environment"        { type = string; default = "dev"          }
variable "do_region"          { type = string; default = "${region}"     }
variable "do_token"           { type = string; sensitive = true; description = "DigitalOcean API token" }
variable "node_count"         { type = number; default = 2              }
variable "node_size"          { type = string; default = "s-2vcpu-4gb"  }
variable "db_size"            { type = string; default = "db-s-1vcpu-1gb" }
variable "db_engine"          { type = string; default = "pg"           }
variable "db_version"         { type = string; default = "16"           }
variable "storage_size_gb"    { type = number; default = 50             }
variable "log_retention_days" { type = number; default = 7              }
variable "k8s_version"        { type = string; default = "1.29"         }`;

  files["networking.tf"] = banner("DigitalOcean", "networking.tf", "VPC & firewall rules") + `
resource "digitalocean_project" "main" {
  name        = "\${var.project_name}-\${var.environment}"
  description = "\${var.project_name} \${var.environment} infrastructure"
  environment = var.environment == "prod" ? "Production" : var.environment == "staging" ? "Staging" : "Development"
}

resource "digitalocean_vpc" "main" {
  name   = "\${var.project_name}-vpc-\${var.environment}"
  region = var.do_region
  ip_range = "10.10.0.0/16"
}

resource "digitalocean_firewall" "app" {
  name = "\${var.project_name}-fw-\${var.environment}"

  inbound_rule {
    protocol         = "tcp"
    port_range       = "443"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }

  inbound_rule {
    protocol         = "tcp"
    port_range       = "80"
    source_addresses = ["0.0.0.0/0", "::/0"]
  }

  outbound_rule {
    protocol              = "tcp"
    port_range            = "all"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }

  outbound_rule {
    protocol              = "udp"
    port_range            = "all"
    destination_addresses = ["0.0.0.0/0", "::/0"]
  }
}`;

  if (has(services, "control-plane", "vm-instance")) {
    files["compute.tf"] = banner("DigitalOcean", "compute.tf", "DOKS Kubernetes cluster") + `
resource "digitalocean_kubernetes_cluster" "main" {
  name    = "\${var.project_name}-doks-\${var.environment}"
  region  = var.do_region
  version = var.k8s_version
  vpc_uuid = digitalocean_vpc.main.id

  node_pool {
    name       = "\${var.project_name}-pool-\${var.environment}"
    size       = var.node_size
    node_count = var.node_count
    auto_scale = var.environment == "prod"
    min_nodes  = var.environment == "prod" ? 2 : null
    max_nodes  = var.environment == "prod" ? 6 : null
    tags       = [var.project_name, var.environment]
  }

  tags = [var.project_name, var.environment]
}

resource "digitalocean_project_resources" "cluster" {
  project = digitalocean_project.main.id
  resources = [digitalocean_kubernetes_cluster.main.urn]
}`;
  }

  if (has(services, "serverless-compute")) {
    files["serverless.tf"] = banner("DigitalOcean", "serverless.tf", "App Platform (serverless)") + `
resource "digitalocean_app" "main" {
  spec {
    name   = "\${var.project_name}-app-\${var.environment}"
    region = var.do_region

    worker {
      name               = "api"
      github {
        repo           = "your-org/your-repo"
        branch         = var.environment == "prod" ? "main" : var.environment
        deploy_on_push = true
      }
      instance_size_slug = var.environment == "prod" ? "professional-xs" : "basic-xxs"
      instance_count     = var.node_count
    }
  }
}`;
  }

  if (has(services, "managed-database", "database")) {
    files["database.tf"] = banner("DigitalOcean", "database.tf", "Managed PostgreSQL cluster") + `
resource "digitalocean_database_cluster" "main" {
  name       = "\${var.project_name}-db-\${var.environment}"
  engine     = var.db_engine
  version    = var.db_version
  size       = var.db_size
  region     = var.do_region
  node_count = var.environment == "prod" ? 3 : 1
  private_network_uuid = digitalocean_vpc.main.id
  tags       = [var.project_name, var.environment]
}

resource "digitalocean_database_db" "main" {
  cluster_id = digitalocean_database_cluster.main.id
  name       = var.project_name
}

resource "digitalocean_database_user" "app" {
  cluster_id = digitalocean_database_cluster.main.id
  name       = "appuser"
}

resource "digitalocean_database_firewall" "main" {
  cluster_id = digitalocean_database_cluster.main.id

  rule {
    type  = "tag"
    value = var.environment
  }
}

resource "digitalocean_project_resources" "db" {
  project   = digitalocean_project.main.id
  resources = [digitalocean_database_cluster.main.urn]
}`;
  }

  if (has(services, "block-storage", "object-storage", "file-storage")) {
    files["storage.tf"] = banner("DigitalOcean", "storage.tf", "Spaces Object Storage") + `
resource "digitalocean_spaces_bucket" "main" {
  name   = "\${var.project_name}-\${var.environment}-data"
  region = var.do_region
  acl    = "private"

  versioning {
    enabled = var.environment == "prod"
  }

  lifecycle_rule {
    enabled = true
    expiration { days = 365 }
  }
}

resource "digitalocean_spaces_bucket_cors_configuration" "main" {
  bucket = digitalocean_spaces_bucket.main.name
  region = digitalocean_spaces_bucket.main.region

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "PUT", "POST"]
    allowed_origins = ["*"]
    max_age_seconds = 3000
  }
}

resource "digitalocean_project_resources" "spaces" {
  project   = digitalocean_project.main.id
  resources = [digitalocean_spaces_bucket.main.urn]
}`;
  }

  if (has(services, "load-balancer")) {
    files["loadbalancer.tf"] = banner("DigitalOcean", "loadbalancer.tf", "Load Balancer") + `
resource "digitalocean_loadbalancer" "main" {
  name   = "\${var.project_name}-lb-\${var.environment}"
  region = var.do_region
  vpc_uuid = digitalocean_vpc.main.id

  forwarding_rule {
    entry_port      = 443
    entry_protocol  = "https"
    target_port     = 80
    target_protocol = "http"
    tls_passthrough = false
  }

  healthcheck {
    port     = 8080
    protocol = "http"
    path     = "/health"
  }

  tags = [var.project_name, var.environment]
}

resource "digitalocean_project_resources" "lb" {
  project   = digitalocean_project.main.id
  resources = [digitalocean_loadbalancer.main.urn]
}`;
  }

  files["outputs.tf"] = banner("DigitalOcean", "outputs.tf", "Resource identifiers") + `
output "vpc_id"      { value = digitalocean_vpc.main.id }
output "project_id"  { value = digitalocean_project.main.id }` +
    (has(services, "control-plane", "vm-instance") ? `
output "cluster_id"       { value = digitalocean_kubernetes_cluster.main.id }
output "cluster_endpoint" { value = digitalocean_kubernetes_cluster.main.endpoint }` : "") +
    (has(services, "managed-database", "database") ? `
output "db_host"     { value = digitalocean_database_cluster.main.private_host; sensitive = true }
output "db_port"     { value = digitalocean_database_cluster.main.port }
output "db_uri"      { value = digitalocean_database_cluster.main.private_uri; sensitive = true }` : "") +
    (has(services, "block-storage", "object-storage", "file-storage") ? `
output "spaces_bucket_name"     { value = digitalocean_spaces_bucket.main.name }
output "spaces_bucket_endpoint" { value = digitalocean_spaces_bucket.main.bucket_domain_name }` : "");

  return files;
}

// ── Linode / Akamai ───────────────────────────────────────────────────────────

function linodeFiles(services: string[], region: string): Record<string, string> {
  const files: Record<string, string> = {};

  files["main.tf"] = banner("Linode / Akamai", "main.tf", "Provider & Terraform settings") + `
terraform {
  required_version = ">= 1.5"
  required_providers {
    linode = {
      source  = "linode/linode"
      version = "~> 2.20"
    }
  }
}

provider "linode" {
  token = var.linode_token
}

# HOW TO USE:
#   export LINODE_TOKEN="<your-api-token>"
#   terraform init
#   terraform apply -var-file="dev.tfvars"
#
# Docs: https://registry.terraform.io/providers/linode/linode/latest/docs`;

  files["variables.tf"] = banner("Linode / Akamai", "variables.tf", "Input variables") + `
variable "project_name"       { type = string; default = "myapp"         }
variable "environment"        { type = string; default = "dev"           }
variable "linode_region"      { type = string; default = "${region}"      }
variable "linode_token"       { type = string; sensitive = true; description = "Linode API token" }
variable "node_count"         { type = number; default = 2               }
variable "node_type"          { type = string; default = "g6-standard-2" }
variable "db_engine_id"       { type = string; default = "postgresql/14"  }
variable "db_type"            { type = string; default = "g6-nanode-1"   }
variable "storage_quota"      { type = number; default = 250             }
variable "k8s_version"        { type = string; default = "1.29"          }
variable "log_retention_days" { type = number; default = 7               }`;

  files["networking.tf"] = banner("Linode / Akamai", "networking.tf", "VPC & firewall") + `
resource "linode_vpc" "main" {
  label  = "\${var.project_name}-vpc-\${var.environment}"
  region = var.linode_region
}

resource "linode_vpc_subnet" "private" {
  vpc_id = linode_vpc.main.id
  label  = "\${var.project_name}-subnet-private-\${var.environment}"
  ipv4   = "10.0.1.0/24"
}

resource "linode_vpc_subnet" "public" {
  vpc_id = linode_vpc.main.id
  label  = "\${var.project_name}-subnet-public-\${var.environment}"
  ipv4   = "10.0.2.0/24"
}

resource "linode_firewall" "app" {
  label = "\${var.project_name}-fw-\${var.environment}"

  inbound {
    label    = "allow-https"
    action   = "ACCEPT"
    protocol = "TCP"
    ports    = "443"
    ipv4     = ["0.0.0.0/0"]
    ipv6     = ["::/0"]
  }

  inbound {
    label    = "allow-http"
    action   = "ACCEPT"
    protocol = "TCP"
    ports    = "80"
    ipv4     = ["0.0.0.0/0"]
    ipv6     = ["::/0"]
  }

  inbound_policy  = "DROP"
  outbound_policy = "ACCEPT"
}`;

  if (has(services, "control-plane", "vm-instance")) {
    files["compute.tf"] = banner("Linode / Akamai", "compute.tf", "LKE Kubernetes cluster") + `
resource "linode_lke_cluster" "main" {
  label       = "\${var.project_name}-lke-\${var.environment}"
  k8s_version = var.k8s_version
  region      = var.linode_region

  pool {
    type  = var.node_type
    count = var.node_count

    autoscaler {
      min = var.environment == "prod" ? 2 : 1
      max = var.environment == "prod" ? 8 : 3
    }
  }

  tags = [var.project_name, var.environment]
}`;
  }

  if (has(services, "serverless-compute")) {
    files["serverless.tf"] = banner("Linode / Akamai", "serverless.tf", "Linode instances (serverless-style)") + `
# Linode does not offer a native FaaS/serverless product.
# Using small Linode instances configured for function-style workloads.

resource "linode_instance" "worker" {
  count  = var.node_count
  label  = "\${var.project_name}-worker-\${var.environment}-\${count.index}"
  region = var.linode_region
  type   = "g6-nanode-1"

  interface {
    purpose   = "vpc"
    subnet_id = linode_vpc_subnet.private.id
  }

  tags = [var.project_name, var.environment]
}`;
  }

  if (has(services, "managed-database", "database")) {
    files["database.tf"] = banner("Linode / Akamai", "database.tf", "Managed PostgreSQL cluster") + `
resource "linode_database_postgresql" "main" {
  label           = "\${var.project_name}-db-\${var.environment}"
  engine_id       = var.db_engine_id
  region          = var.linode_region
  type            = var.db_type
  cluster_size    = var.environment == "prod" ? 3 : 1
  replication_type = var.environment == "prod" ? "asynch" : "none"
  ssl_connection  = true

  allow_list = ["0.0.0.0/0"]
}`;
  }

  if (has(services, "block-storage", "object-storage", "file-storage")) {
    files["storage.tf"] = banner("Linode / Akamai", "storage.tf", "Object Storage bucket") + `
resource "linode_object_storage_bucket" "main" {
  cluster = "\${var.linode_region}-1"
  label   = "\${var.project_name}-\${var.environment}-data"
  acl     = "private"

  lifecycle_rule {
    id      = "expire-old"
    enabled = true
    expiration { days = 365 }
  }
}

resource "linode_object_storage_key" "main" {
  label = "\${var.project_name}-\${var.environment}-key"
}`;
  }

  if (has(services, "load-balancer")) {
    files["loadbalancer.tf"] = banner("Linode / Akamai", "loadbalancer.tf", "NodeBalancer") + `
resource "linode_nodebalancer" "main" {
  label  = "\${var.project_name}-nb-\${var.environment}"
  region = var.linode_region
  client_conn_throttle = var.environment == "prod" ? 0 : 20
  tags   = [var.project_name, var.environment]
}

resource "linode_nodebalancer_config" "https" {
  nodebalancer_id = linode_nodebalancer.main.id
  port            = 443
  protocol        = "https"
  algorithm       = "roundrobin"
  stickiness      = "http_cookie"
  check           = "http"
  check_path      = "/health"
  check_interval  = 10
  check_timeout   = 5
  check_attempts  = 3
}`;
  }

  files["outputs.tf"] = banner("Linode / Akamai", "outputs.tf", "Resource identifiers") + `
output "vpc_id"             { value = linode_vpc.main.id }
output "private_subnet_id"  { value = linode_vpc_subnet.private.id }
output "public_subnet_id"   { value = linode_vpc_subnet.public.id }` +
    (has(services, "control-plane", "vm-instance") ? `
output "cluster_id"   { value = linode_lke_cluster.main.id }
output "kubeconfig"   { value = linode_lke_cluster.main.kubeconfig; sensitive = true }` : "") +
    (has(services, "managed-database", "database") ? `
output "db_host"     { value = linode_database_postgresql.main.host_primary; sensitive = true }
output "db_port"     { value = linode_database_postgresql.main.port }` : "") +
    (has(services, "block-storage", "object-storage", "file-storage") ? `
output "bucket_hostname" { value = linode_object_storage_bucket.main.hostname }` : "");

  return files;
}

// ── Public API ────────────────────────────────────────────────────────────────

export function generateAltTerraformFiles(
  cloud: AltTfCloud,
  services: string[],
  region: string
): Record<string, string> {
  switch (cloud) {
    case "ibm":     return ibmFiles(services, region);
    case "oci":     return ociFiles(services, region);
    case "alibaba": return alibabaFiles(services, region);
    case "do":      return doFiles(services, region);
    case "linode":  return linodeFiles(services, region);
  }
}

export function generateAltTerraform(
  cloud: AltTfCloud,
  services: string[],
  region: string
): string {
  return Object.values(generateAltTerraformFiles(cloud, services, region)).join("\n\n");
}

export function generateAltTfvars(
  cloud: AltTfCloud,
  env: "dev" | "staging" | "prod",
  region: string,
  services: string[]
): string {
  const hasK8s    = has(services, "control-plane", "vm-instance");
  const hasDb     = has(services, "managed-database", "database");
  const hasStore  = has(services, "block-storage", "object-storage", "file-storage");

  const configs = {
    ibm: {
      regionKey: "ibm_region",
      dev:     { node_count: 1, machine_type: "bx2.2x8",   db_plan: "standard" },
      staging: { node_count: 2, machine_type: "bx2.4x16",  db_plan: "standard" },
      prod:    { node_count: 3, machine_type: "bx2.8x32",  db_plan: "enterprise" },
    },
    oci: {
      regionKey: "oci_region",
      dev:     { node_count: 1, node_shape: "VM.Standard.E4.Flex", node_ocpus: 1,  node_memory_gb: 8  },
      staging: { node_count: 2, node_shape: "VM.Standard.E4.Flex", node_ocpus: 2,  node_memory_gb: 16 },
      prod:    { node_count: 3, node_shape: "VM.Standard.E4.Flex", node_ocpus: 4,  node_memory_gb: 32 },
    },
    alibaba: {
      regionKey: "alicloud_region",
      dev:     { node_count: 1, instance_type: "ecs.c6.large",   db_instance_class: "rds.mysql.s1.small" },
      staging: { node_count: 2, instance_type: "ecs.c6.xlarge",  db_instance_class: "rds.mysql.s2.large" },
      prod:    { node_count: 3, instance_type: "ecs.c6.2xlarge", db_instance_class: "rds.mysql.c1.xlarge" },
    },
    do: {
      regionKey: "do_region",
      dev:     { node_count: 1, node_size: "s-1vcpu-2gb",  db_size: "db-s-1vcpu-1gb" },
      staging: { node_count: 2, node_size: "s-2vcpu-4gb",  db_size: "db-s-2vcpu-4gb" },
      prod:    { node_count: 3, node_size: "s-4vcpu-8gb",  db_size: "db-s-4vcpu-8gb" },
    },
    linode: {
      regionKey: "linode_region",
      dev:     { node_count: 1, node_type: "g6-nanode-1",   db_type: "g6-nanode-1"  },
      staging: { node_count: 2, node_type: "g6-standard-2", db_type: "g6-standard-1" },
      prod:    { node_count: 3, node_type: "g6-standard-4", db_type: "g6-standard-2" },
    },
  };

  const cloudCfg = configs[cloud];
  const envCfg   = cloudCfg[env] as Record<string, string | number>;
  const regionKey = cloudCfg.regionKey;

  const lines = [
    `# ${"═".repeat(58)}`,
    `# ${env.toUpperCase()} Environment — ${env}.tfvars`,
    `# Apply with: terraform apply -var-file="${env}.tfvars"`,
    `# ${"═".repeat(58)}`,
    ``,
    `project_name = "myapp"`,
    `environment  = "${env}"`,
    `${regionKey} = "${region}"`,
    ``,
    `# ── Compute ${"─".repeat(49)}`,
  ];

  if (hasK8s) {
    Object.entries(envCfg).forEach(([k, v]) => {
      if (k !== "db_plan" && k !== "db_size" && k !== "db_type" && k !== "db_instance_class") {
        lines.push(`${k} = ${typeof v === "string" ? `"${v}"` : v}`);
      }
    });
  }

  if (hasDb) {
    lines.push(``, `# ── Database ${"─".repeat(48)}`);
    const dbKey = cloud === "ibm" ? "db_plan" : cloud === "do" ? "db_size" : cloud === "linode" ? "db_type" : "db_instance_class";
    if (dbKey in envCfg) {
      lines.push(`${dbKey} = "${envCfg[dbKey]}"`);
    }
    lines.push(`enable_backups = ${env !== "dev"}`);
  }

  if (hasStore) {
    lines.push(``, `# ── Storage ${"─".repeat(49)}`,
      `storage_size_gb = ${env === "dev" ? 20 : env === "staging" ? 50 : 100}`);
  }

  lines.push(
    ``, `# ── Feature flags ${"─".repeat(42)}`,
    `enable_monitoring  = ${env !== "dev"}`,
    `log_retention_days = ${env === "dev" ? 7 : env === "staging" ? 14 : 30}`
  );

  return lines.join("\n");
}
