// Generates runnable Terraform HCL for AWS / Azure / GCP based on selected services.
// Pure string output — no project imports, no side effects.

export type TfCloud = "eks" | "aks" | "gke";

const TODAY = new Date().toISOString().slice(0, 10);

function header(cloud: string, region: string, services: string[]): string {
  const cred =
    cloud === "AWS"
      ? "#   AWS:   aws configure  (or set AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY)"
      : cloud === "Azure"
      ? "#   Azure: az login"
      : "#   GCP:   gcloud auth application-default login";
  return `# ${"═".repeat(62)}
# Generated by TechAtlas — Cloud Infrastructure Terraform
# Cloud:    ${cloud}
# Region:   ${region}
# Services: ${services.join(", ")}
# Generated: ${TODAY}
# ${"═".repeat(62)}
# HOW TO USE:
#   1. terraform init
#   2. terraform plan -var="project_name=myapp"
#   3. terraform apply -var="project_name=myapp"
# PREREQUISITES — configure credentials first:
${cred}
# ${"═".repeat(62)}
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// AWS
// ─────────────────────────────────────────────────────────────────────────────
function generateAws(services: string[], region: string): string {
  const has = (id: string) => services.includes(id);
  const needsVpc =
    services.some(s =>
      [
        "vpc","internet-gateway","public-subnet","private-subnet","nat-gateway",
        "route-table","nacl","security-group","app-load-balancer","load-balancer",
        "control-plane","vm-instance","serverless-compute","functions",
        "managed-database","cache","bastion-host","block-storage","file-storage",
        "elastic-ip","vpn-gateway",
      ].includes(s)
    );

  const lines: string[] = [];
  lines.push(header("AWS", region, services));

  // ── terraform + provider ──────────────────────────────────────────────────
  lines.push(`terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  # Uncomment to use S3 remote state:
  # backend "s3" {
  #   bucket = "my-terraform-state"
  #   key    = "infra/terraform.tfstate"
  #   region = "${region}"
  # }
}

provider "aws" {
  region = var.aws_region
  default_tags {
    tags = local.common_tags
  }
}
`);

  // ── variables ─────────────────────────────────────────────────────────────
  lines.push(`# ── Variables ${"─".repeat(50)}
variable "aws_region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "${region}"
}
variable "project_name" {
  description = "Project name prefix for resource naming"
  type        = string
  default     = "myapp"
}
variable "environment" {
  description = "Deployment environment (dev | staging | prod)"
  type        = string
  default     = "prod"
}
variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"
}
${has("bastion-host") ? `variable "ssh_key_name" {
  description = "EC2 key pair name for Bastion SSH access"
  type        = string
  default     = "my-key-pair"
}` : ""}
${has("dns") ? `variable "domain_name" {
  description = "Root domain name for Route 53"
  type        = string
  default     = "example.com"
}` : ""}
${has("managed-database") ? `variable "db_password" {
  description = "Master password for the RDS instance"
  type        = string
  sensitive   = true
  default     = "ChangeMe123!"
}` : ""}
`);

  // ── locals ────────────────────────────────────────────────────────────────
  lines.push(`# ── Locals ${"─".repeat(53)}
locals {
  name_prefix = "\${var.project_name}-\${var.environment}"
  common_tags = {
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "terraform"
    GeneratedBy = "TechAtlas"
  }
}
`);

  // ── data sources ──────────────────────────────────────────────────────────
  if (needsVpc) {
    lines.push(`# ── Data Sources ${"─".repeat(47)}
data "aws_availability_zones" "available" {
  state = "available"
}
`);
  }

  // ── VPC + Networking ──────────────────────────────────────────────────────
  if (needsVpc) {
    lines.push(`# ── VPC & Networking ${"─".repeat(43)}
resource "aws_vpc" "main" {
  cidr_block           = var.vpc_cidr
  enable_dns_support   = true
  enable_dns_hostnames = true
  tags = { Name = "\${local.name_prefix}-vpc" }
}
`);

    if (has("internet-gateway") || has("public-subnet") || has("nat-gateway") || has("app-load-balancer") || has("load-balancer") || has("bastion-host")) {
      lines.push(`resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
  tags   = { Name = "\${local.name_prefix}-igw" }
}
`);
    }

    if (has("public-subnet") || has("nat-gateway") || has("app-load-balancer") || has("load-balancer") || has("bastion-host")) {
      lines.push(`resource "aws_subnet" "public" {
  count                   = 2
  vpc_id                  = aws_vpc.main.id
  cidr_block              = cidrsubnet(var.vpc_cidr, 8, count.index)
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  map_public_ip_on_launch = true
  tags = { Name = "\${local.name_prefix}-public-\${count.index + 1}" }
}

resource "aws_route_table" "public" {
  vpc_id = aws_vpc.main.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }
  tags = { Name = "\${local.name_prefix}-rt-public" }
}

resource "aws_route_table_association" "public" {
  count          = 2
  subnet_id      = aws_subnet.public[count.index].id
  route_table_id = aws_route_table.public.id
}
`);
    }

    if (has("private-subnet") || has("control-plane") || has("vm-instance") || has("serverless-compute") || has("managed-database") || has("cache") || has("file-storage")) {
      lines.push(`resource "aws_subnet" "private" {
  count             = 2
  vpc_id            = aws_vpc.main.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + 10)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  tags = { Name = "\${local.name_prefix}-private-\${count.index + 1}" }
}
`);
      if (has("nat-gateway")) {
        lines.push(`resource "aws_eip" "nat" {
  domain = "vpc"
  tags   = { Name = "\${local.name_prefix}-eip-nat" }
}

resource "aws_nat_gateway" "main" {
  allocation_id = aws_eip.nat.id
  subnet_id     = aws_subnet.public[0].id
  tags          = { Name = "\${local.name_prefix}-nat" }
  depends_on    = [aws_internet_gateway.main]
}

resource "aws_route_table" "private" {
  vpc_id = aws_vpc.main.id
  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.main.id
  }
  tags = { Name = "\${local.name_prefix}-rt-private" }
}

resource "aws_route_table_association" "private" {
  count          = 2
  subnet_id      = aws_subnet.private[count.index].id
  route_table_id = aws_route_table.private.id
}
`);
      }
    }

    if (has("nacl")) {
      lines.push(`# ── Network ACL ${"─".repeat(48)}
resource "aws_network_acl" "public" {
  vpc_id     = aws_vpc.main.id
  subnet_ids = aws_subnet.public[*].id

  ingress { rule_no = 100; protocol = "tcp"; action = "allow"; cidr_block = "0.0.0.0/0"; from_port = 80;  to_port = 80  }
  ingress { rule_no = 110; protocol = "tcp"; action = "allow"; cidr_block = "0.0.0.0/0"; from_port = 443; to_port = 443 }
  ingress { rule_no = 120; protocol = "tcp"; action = "allow"; cidr_block = "0.0.0.0/0"; from_port = 1024; to_port = 65535 }
  egress  { rule_no = 100; protocol = "-1";  action = "allow"; cidr_block = "0.0.0.0/0"; from_port = 0;   to_port = 0   }
  tags = { Name = "\${local.name_prefix}-nacl-public" }
}

resource "aws_network_acl" "private" {
  vpc_id     = aws_vpc.main.id
  subnet_ids = aws_subnet.private[*].id

  ingress { rule_no = 100; protocol = "-1"; action = "allow"; cidr_block = var.vpc_cidr; from_port = 0; to_port = 0 }
  egress  { rule_no = 100; protocol = "-1"; action = "allow"; cidr_block = "0.0.0.0/0"; from_port = 0; to_port = 0 }
  tags = { Name = "\${local.name_prefix}-nacl-private" }
}
`);
    }

    if (has("security-group") || has("app-load-balancer") || has("vm-instance") || has("managed-database")) {
      lines.push(`# ── Security Groups ${"─".repeat(44)}
resource "aws_security_group" "alb" {
  name        = "\${local.name_prefix}-sg-alb"
  description = "Allow HTTP/HTTPS from internet"
  vpc_id      = aws_vpc.main.id

  ingress { from_port = 80;  to_port = 80;  protocol = "tcp"; cidr_blocks = ["0.0.0.0/0"] }
  ingress { from_port = 443; to_port = 443; protocol = "tcp"; cidr_blocks = ["0.0.0.0/0"] }
  egress  { from_port = 0;   to_port = 0;   protocol = "-1";  cidr_blocks = ["0.0.0.0/0"] }
  tags = { Name = "\${local.name_prefix}-sg-alb" }
}

resource "aws_security_group" "app" {
  name        = "\${local.name_prefix}-sg-app"
  description = "Allow traffic from ALB"
  vpc_id      = aws_vpc.main.id

  ingress { from_port = 8080; to_port = 8080; protocol = "tcp"; security_groups = [aws_security_group.alb.id] }
  egress  { from_port = 0;    to_port = 0;    protocol = "-1";  cidr_blocks     = ["0.0.0.0/0"] }
  tags = { Name = "\${local.name_prefix}-sg-app" }
}

resource "aws_security_group" "db" {
  name        = "\${local.name_prefix}-sg-db"
  description = "Allow DB traffic from app layer"
  vpc_id      = aws_vpc.main.id

  ingress { from_port = 5432; to_port = 5432; protocol = "tcp"; security_groups = [aws_security_group.app.id] }
  ingress { from_port = 3306; to_port = 3306; protocol = "tcp"; security_groups = [aws_security_group.app.id] }
  egress  { from_port = 0;    to_port = 0;    protocol = "-1";  cidr_blocks     = ["0.0.0.0/0"] }
  tags = { Name = "\${local.name_prefix}-sg-db" }
}
`);
    }
  }

  // ── Bastion Host ──────────────────────────────────────────────────────────
  if (has("bastion-host") && needsVpc) {
    lines.push(`# ── Bastion Host ${"─".repeat(47)}
data "aws_ami" "amazon_linux" {
  most_recent = true
  owners      = ["amazon"]
  filter { name = "name";                values = ["al2023-ami-*-x86_64"] }
  filter { name = "virtualization-type"; values = ["hvm"]                 }
}

resource "aws_security_group" "bastion" {
  name        = "\${local.name_prefix}-sg-bastion"
  description = "SSH access to Bastion"
  vpc_id      = aws_vpc.main.id

  ingress { from_port = 22; to_port = 22; protocol = "tcp"; cidr_blocks = ["0.0.0.0/0"] }
  egress  { from_port = 0;  to_port = 0;  protocol = "-1";  cidr_blocks = ["0.0.0.0/0"] }
  tags = { Name = "\${local.name_prefix}-sg-bastion" }
}

resource "aws_instance" "bastion" {
  ami                         = data.aws_ami.amazon_linux.id
  instance_type               = "t3.micro"
  subnet_id                   = aws_subnet.public[0].id
  vpc_security_group_ids      = [aws_security_group.bastion.id]
  key_name                    = var.ssh_key_name
  associate_public_ip_address = true
  tags = { Name = "\${local.name_prefix}-bastion" }
}
`);
  }

  // ── ACM Certificate ───────────────────────────────────────────────────────
  if (has("acm")) {
    lines.push(`# ── ACM TLS Certificate ${"─".repeat(40)}
resource "aws_acm_certificate" "main" {
  domain_name               = "*.example.com"
  subject_alternative_names = ["example.com"]
  validation_method         = "DNS"
  lifecycle { create_before_destroy = true }
  tags = { Name = "\${local.name_prefix}-cert" }
}
`);
  }

  // ── Load Balancers ────────────────────────────────────────────────────────
  if (has("app-load-balancer") && needsVpc) {
    lines.push(`# ── Application Load Balancer ${"─".repeat(34)}
resource "aws_lb" "main" {
  name               = "\${local.name_prefix}-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets            = aws_subnet.public[*].id
  tags               = { Name = "\${local.name_prefix}-alb" }
}

resource "aws_lb_target_group" "app" {
  name        = "\${local.name_prefix}-tg"
  port        = 8080
  protocol    = "HTTP"
  vpc_id      = aws_vpc.main.id
  target_type = "ip"
  health_check { path = "/health"; matcher = "200-399" }
}

resource "aws_lb_listener" "https" {
  load_balancer_arn = aws_lb.main.arn
  port              = 443
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-TLS13-1-2-2021-06"
  ${has("acm") ? `certificate_arn   = aws_acm_certificate.main.arn` : `# certificate_arn = "<your-acm-arn>"`}
  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.app.arn
  }
}

resource "aws_lb_listener" "http_redirect" {
  load_balancer_arn = aws_lb.main.arn
  port              = 80
  protocol          = "HTTP"
  default_action {
    type = "redirect"
    redirect { port = "443"; protocol = "HTTPS"; status_code = "HTTP_301" }
  }
}
`);
  }

  if (has("load-balancer") && needsVpc) {
    lines.push(`# ── Network Load Balancer ${"─".repeat(38)}
resource "aws_lb" "nlb" {
  name               = "\${local.name_prefix}-nlb"
  internal           = false
  load_balancer_type = "network"
  subnets            = aws_subnet.public[*].id
  tags               = { Name = "\${local.name_prefix}-nlb" }
}
`);
  }

  // ── EKS Cluster ──────────────────────────────────────────────────────────
  if (has("control-plane") && needsVpc) {
    lines.push(`# ── EKS Cluster ${"─".repeat(48)}
resource "aws_iam_role" "eks_cluster" {
  name = "\${local.name_prefix}-eks-cluster-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole"; Effect = "Allow"; Principal = { Service = "eks.amazonaws.com" } }]
  })
}

resource "aws_iam_role_policy_attachment" "eks_cluster_policy" {
  role       = aws_iam_role.eks_cluster.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
}

resource "aws_eks_cluster" "main" {
  name     = "\${local.name_prefix}-eks"
  role_arn = aws_iam_role.eks_cluster.arn
  version  = "1.30"

  vpc_config {
    subnet_ids              = concat(aws_subnet.private[*].id, aws_subnet.public[*].id)
    endpoint_private_access = true
    endpoint_public_access  = true
  }

  depends_on = [aws_iam_role_policy_attachment.eks_cluster_policy]
  tags = { Name = "\${local.name_prefix}-eks" }
}
`);

    if (has("vm-instance")) {
      lines.push(`resource "aws_iam_role" "eks_nodes" {
  name = "\${local.name_prefix}-eks-node-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole"; Effect = "Allow"; Principal = { Service = "ec2.amazonaws.com" } }]
  })
}

resource "aws_iam_role_policy_attachment" "eks_worker"    { role = aws_iam_role.eks_nodes.name; policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"            }
resource "aws_iam_role_policy_attachment" "eks_cni"       { role = aws_iam_role.eks_nodes.name; policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"               }
resource "aws_iam_role_policy_attachment" "eks_ecr"       { role = aws_iam_role.eks_nodes.name; policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly" }

resource "aws_eks_node_group" "main" {
  cluster_name    = aws_eks_cluster.main.name
  node_group_name = "\${local.name_prefix}-nodes"
  node_role_arn   = aws_iam_role.eks_nodes.arn
  subnet_ids      = aws_subnet.private[*].id
  instance_types  = ["t3.medium"]

  scaling_config { desired_size = 2; min_size = 1; max_size = 4 }
  update_config  { max_unavailable = 1 }

  depends_on = [aws_iam_role_policy_attachment.eks_worker, aws_iam_role_policy_attachment.eks_cni, aws_iam_role_policy_attachment.eks_ecr]
  tags = { Name = "\${local.name_prefix}-node-group" }
}
`);
    }
  } else if (has("vm-instance") && needsVpc) {
    lines.push(`# ── EC2 Instance ${"─".repeat(47)}
data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]
  filter { name = "name";                values = ["al2023-ami-*-x86_64"] }
  filter { name = "virtualization-type"; values = ["hvm"]                 }
}

resource "aws_instance" "app" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = "t3.medium"
  subnet_id              = aws_subnet.private[0].id
  vpc_security_group_ids = [aws_security_group.app.id]
  tags = { Name = "\${local.name_prefix}-app" }
}
`);
  }

  // ── Serverless / ECS Fargate ──────────────────────────────────────────────
  if (has("serverless-compute") && needsVpc) {
    lines.push(`# ── ECS Fargate ${"─".repeat(48)}
resource "aws_ecs_cluster" "main" {
  name = "\${local.name_prefix}-ecs"
  setting { name = "containerInsights"; value = "enabled" }
  tags = { Name = "\${local.name_prefix}-ecs" }
}

resource "aws_iam_role" "ecs_task_exec" {
  name = "\${local.name_prefix}-ecs-exec-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole"; Effect = "Allow"; Principal = { Service = "ecs-tasks.amazonaws.com" } }]
  })
}

resource "aws_iam_role_policy_attachment" "ecs_exec" {
  role       = aws_iam_role.ecs_task_exec.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_ecs_task_definition" "app" {
  family                   = "\${local.name_prefix}-task"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "512"
  memory                   = "1024"
  execution_role_arn       = aws_iam_role.ecs_task_exec.arn
  container_definitions = jsonencode([{
    name  = "app"
    image = "nginx:latest"
    portMappings = [{ containerPort = 80; hostPort = 80; protocol = "tcp" }]
    logConfiguration = {
      logDriver = "awslogs"
      options = { "awslogs-group" = "/ecs/\${local.name_prefix}"; "awslogs-region" = var.aws_region; "awslogs-stream-prefix" = "ecs" }
    }
  }])
}

resource "aws_ecs_service" "app" {
  name            = "\${local.name_prefix}-svc"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.app.arn
  desired_count   = 2
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = aws_subnet.private[*].id
    security_groups  = [aws_security_group.app.id]
    assign_public_ip = false
  }
}
`);
  }

  // ── Lambda Functions ──────────────────────────────────────────────────────
  if (has("functions")) {
    lines.push(`# ── Lambda Functions ${"─".repeat(43)}
resource "aws_iam_role" "lambda" {
  name = "\${local.name_prefix}-lambda-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole"; Effect = "Allow"; Principal = { Service = "lambda.amazonaws.com" } }]
  })
}

resource "aws_iam_role_policy_attachment" "lambda_basic" {
  role       = aws_iam_role.lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_cloudwatch_log_group" "lambda" {
  name              = "/aws/lambda/\${local.name_prefix}-fn"
  retention_in_days = 30
}

resource "aws_lambda_function" "main" {
  function_name = "\${local.name_prefix}-fn"
  role          = aws_iam_role.lambda.arn
  handler       = "index.handler"
  runtime       = "nodejs20.x"
  timeout       = 30
  memory_size   = 512

  # Replace with actual deployment package
  filename         = "lambda.zip"
  source_code_hash = filebase64sha256("lambda.zip")

  environment {
    variables = { ENV = var.environment }
  }

  depends_on = [aws_cloudwatch_log_group.lambda]
  tags = { Name = "\${local.name_prefix}-fn" }
}
`);
  }

  // ── Container Registry ────────────────────────────────────────────────────
  if (has("registry")) {
    lines.push(`# ── ECR Container Registry ${"─".repeat(37)}
resource "aws_ecr_repository" "main" {
  name                 = "\${local.name_prefix}/app"
  image_tag_mutability = "MUTABLE"
  image_scanning_configuration { scan_on_push = true }
  tags = { Name = "\${local.name_prefix}-ecr" }
}

resource "aws_ecr_lifecycle_policy" "main" {
  repository = aws_ecr_repository.main.name
  policy = jsonencode({
    rules = [{
      rulePriority = 1
      description  = "Keep last 10 images"
      selection    = { tagStatus = "any"; countType = "imageCountMoreThan"; countNumber = 10 }
      action       = { type = "expire" }
    }]
  })
}
`);
  }

  // ── RDS Managed Database ──────────────────────────────────────────────────
  if (has("managed-database") && needsVpc) {
    lines.push(`# ── RDS PostgreSQL ${"─".repeat(45)}
resource "aws_db_subnet_group" "main" {
  name       = "\${local.name_prefix}-db-subnet-group"
  subnet_ids = aws_subnet.private[*].id
  tags = { Name = "\${local.name_prefix}-db-subnet-group" }
}

resource "aws_db_instance" "main" {
  identifier              = "\${local.name_prefix}-postgres"
  engine                  = "postgres"
  engine_version          = "16.2"
  instance_class          = "db.t3.medium"
  allocated_storage       = 20
  max_allocated_storage   = 100
  storage_type            = "gp3"
  db_name                 = "appdb"
  username                = "dbadmin"
  password                = var.db_password
  db_subnet_group_name    = aws_db_subnet_group.main.name
  vpc_security_group_ids  = [aws_security_group.db.id]
  multi_az                = true
  backup_retention_period = 7
  deletion_protection     = true
  skip_final_snapshot     = false
  final_snapshot_identifier = "\${local.name_prefix}-postgres-final"
  tags = { Name = "\${local.name_prefix}-postgres" }
}
`);
  }

  // ── ElastiCache Redis ─────────────────────────────────────────────────────
  if (has("cache") && needsVpc) {
    lines.push(`# ── ElastiCache Redis ${"─".repeat(42)}
resource "aws_elasticache_subnet_group" "main" {
  name       = "\${local.name_prefix}-cache-subnet-group"
  subnet_ids = aws_subnet.private[*].id
}

resource "aws_elasticache_cluster" "main" {
  cluster_id           = "\${local.name_prefix}-redis"
  engine               = "redis"
  node_type            = "cache.t3.micro"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis7"
  port                 = 6379
  subnet_group_name    = aws_elasticache_subnet_group.main.name
  security_group_ids   = [aws_security_group.db.id]
  tags = { Name = "\${local.name_prefix}-redis" }
}
`);
  }

  // ── EBS Block Storage ─────────────────────────────────────────────────────
  if (has("block-storage")) {
    lines.push(`# ── EBS Block Storage ${"─".repeat(42)}
resource "aws_ebs_volume" "main" {
  availability_zone = data.aws_availability_zones.available.names[0]
  size              = 50
  type              = "gp3"
  iops              = 3000
  throughput        = 125
  encrypted         = true
  tags = { Name = "\${local.name_prefix}-ebs" }
}
`);
  }

  // ── EFS File Storage ──────────────────────────────────────────────────────
  if (has("file-storage") && needsVpc) {
    lines.push(`# ── EFS File Storage ${"─".repeat(43)}
resource "aws_efs_file_system" "main" {
  creation_token   = "\${local.name_prefix}-efs"
  performance_mode = "generalPurpose"
  throughput_mode  = "bursting"
  encrypted        = true
  tags = { Name = "\${local.name_prefix}-efs" }
}

resource "aws_efs_mount_target" "main" {
  count           = 2
  file_system_id  = aws_efs_file_system.main.id
  subnet_id       = aws_subnet.private[count.index].id
  security_groups = [aws_security_group.app.id]
}
`);
  }

  // ── S3 Object Storage ─────────────────────────────────────────────────────
  if (has("object-storage")) {
    lines.push(`# ── S3 Object Storage ${"─".repeat(42)}
resource "aws_s3_bucket" "main" {
  bucket = "\${local.name_prefix}-assets-\${data.aws_caller_identity.current.account_id}"
  tags   = { Name = "\${local.name_prefix}-assets" }
}

data "aws_caller_identity" "current" {}

resource "aws_s3_bucket_versioning" "main" {
  bucket = aws_s3_bucket.main.id
  versioning_configuration { status = "Enabled" }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "main" {
  bucket = aws_s3_bucket.main.id
  rule { apply_server_side_encryption_by_default { sse_algorithm = "aws:kms" } }
}

resource "aws_s3_bucket_public_access_block" "main" {
  bucket                  = aws_s3_bucket.main.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
`);
  }

  // ── Secrets Manager ───────────────────────────────────────────────────────
  if (has("secrets-manager")) {
    lines.push(`# ── Secrets Manager ${"─".repeat(44)}
resource "aws_secretsmanager_secret" "app" {
  name                    = "\${local.name_prefix}/app/secrets"
  recovery_window_in_days = 7
  tags = { Name = "\${local.name_prefix}-secret" }
}

resource "aws_secretsmanager_secret_version" "app" {
  secret_id     = aws_secretsmanager_secret.app.id
  secret_string = jsonencode({ DB_PASSWORD = "REPLACE_ME"; API_KEY = "REPLACE_ME" })
}
`);
  }

  // ── CloudWatch Monitoring ─────────────────────────────────────────────────
  if (has("monitoring-logging")) {
    lines.push(`# ── CloudWatch Monitoring & Logging ${"─".repeat(28)}
resource "aws_cloudwatch_log_group" "app" {
  name              = "/aws/\${local.name_prefix}"
  retention_in_days = 30
  tags = { Name = "\${local.name_prefix}-logs" }
}

resource "aws_cloudwatch_metric_alarm" "cpu_high" {
  alarm_name          = "\${local.name_prefix}-cpu-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EC2"
  period              = 300
  statistic           = "Average"
  threshold           = 80
  alarm_description   = "CPU utilisation exceeded 80%"
  tags = { Name = "\${local.name_prefix}-cpu-alarm" }
}
`);
  }

  // ── Route 53 DNS ──────────────────────────────────────────────────────────
  if (has("dns")) {
    lines.push(`# ── Route 53 DNS ${"─".repeat(47)}
resource "aws_route53_zone" "main" {
  name = var.domain_name
  tags = { Name = "\${local.name_prefix}-zone" }
}
`);
  }

  // ── WAF ───────────────────────────────────────────────────────────────────
  if (has("waf")) {
    lines.push(`# ── WAFv2 Web ACL ${"─".repeat(46)}
resource "aws_wafv2_web_acl" "main" {
  name  = "\${local.name_prefix}-waf"
  scope = "REGIONAL"

  default_action { allow {} }

  rule {
    name     = "AWSManagedRulesCommon"
    priority = 1
    override_action { none {} }
    statement { managed_rule_group_statement { name = "AWSManagedRulesCommonRuleSet"; vendor_name = "AWS" } }
    visibility_config { cloudwatch_metrics_enabled = true; metric_name = "common-rules"; sampled_requests_enabled = true }
  }

  rule {
    name     = "AWSManagedRulesSQLi"
    priority = 2
    override_action { none {} }
    statement { managed_rule_group_statement { name = "AWSManagedRulesSQLiRuleSet"; vendor_name = "AWS" } }
    visibility_config { cloudwatch_metrics_enabled = true; metric_name = "sqli-rules"; sampled_requests_enabled = true }
  }

  visibility_config { cloudwatch_metrics_enabled = true; metric_name = "\${local.name_prefix}-waf"; sampled_requests_enabled = true }
  tags = { Name = "\${local.name_prefix}-waf" }
}
`);
  }

  // ── CloudFront CDN ────────────────────────────────────────────────────────
  if (has("cdn")) {
    lines.push(`# ── CloudFront CDN ${"─".repeat(45)}
resource "aws_cloudfront_distribution" "main" {
  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"
  price_class         = "PriceClass_100"

  ${has("object-storage") ? `origin {
    domain_name              = aws_s3_bucket.main.bucket_regional_domain_name
    origin_id                = "S3-\${aws_s3_bucket.main.id}"
    origin_access_control_id = aws_cloudfront_origin_access_control.main.id
  }

  resource "aws_cloudfront_origin_access_control" "main" {
    name                              = "\${local.name_prefix}-oac"
    origin_access_control_origin_type = "s3"
    signing_behavior                  = "always"
    signing_protocol                  = "sigv4"
  }` : `origin {
    domain_name = ${has("app-load-balancer") ? "aws_lb.main.dns_name" : `"example.com"`}
    origin_id   = "ALB-origin"
    custom_origin_config { http_port = 80; https_port = 443; origin_protocol_policy = "https-only"; origin_ssl_protocols = ["TLSv1.2"] }
  }`}

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = ${has("object-storage") ? `"S3-\${aws_s3_bucket.main.id}"` : `"ALB-origin"`}
    viewer_protocol_policy = "redirect-to-https"
    compress               = true
    cache_policy_id        = "658327ea-f89d-4fab-a63d-7e88639e58f6" # CachingOptimized
  }

  restrictions { geo_restriction { restriction_type = "none" } }
  viewer_certificate { cloudfront_default_certificate = true }
  tags = { Name = "\${local.name_prefix}-cdn" }
}
`);
  }

  // ── API Gateway ───────────────────────────────────────────────────────────
  if (has("api-gateway")) {
    lines.push(`# ── API Gateway (HTTP) ${"─".repeat(41)}
resource "aws_apigatewayv2_api" "main" {
  name          = "\${local.name_prefix}-api"
  protocol_type = "HTTP"
  cors_configuration {
    allow_origins = ["*"]
    allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers = ["Content-Type", "Authorization"]
    max_age       = 300
  }
  tags = { Name = "\${local.name_prefix}-api" }
}

resource "aws_apigatewayv2_stage" "main" {
  api_id      = aws_apigatewayv2_api.main.id
  name        = var.environment
  auto_deploy = true
}
`);
  }

  // ── SQS Message Queue ─────────────────────────────────────────────────────
  if (has("message-queue")) {
    lines.push(`# ── SQS Message Queue ${"─".repeat(42)}
resource "aws_sqs_queue" "dlq" {
  name                       = "\${local.name_prefix}-dlq"
  message_retention_seconds  = 1209600
  tags = { Name = "\${local.name_prefix}-dlq" }
}

resource "aws_sqs_queue" "main" {
  name                       = "\${local.name_prefix}-queue"
  visibility_timeout_seconds = 30
  message_retention_seconds  = 86400
  redrive_policy = jsonencode({ deadLetterTargetArn = aws_sqs_queue.dlq.arn; maxReceiveCount = 5 })
  tags = { Name = "\${local.name_prefix}-queue" }
}
`);
  }

  // ── EventBridge ───────────────────────────────────────────────────────────
  if (has("event-bus")) {
    lines.push(`# ── EventBridge Event Bus ${"─".repeat(38)}
resource "aws_cloudwatch_event_bus" "main" {
  name = "\${local.name_prefix}-events"
  tags = { Name = "\${local.name_prefix}-events" }
}

resource "aws_cloudwatch_event_rule" "app_events" {
  name           = "\${local.name_prefix}-rule"
  event_bus_name = aws_cloudwatch_event_bus.main.name
  event_pattern = jsonencode({ source = ["\${var.project_name}.app"] })
  tags = { Name = "\${local.name_prefix}-rule" }
}
`);
  }

  // ── VPN Gateway ───────────────────────────────────────────────────────────
  if (has("vpn-gateway") && needsVpc) {
    lines.push(`# ── VPN Gateway ${"─".repeat(48)}
resource "aws_vpn_gateway" "main" {
  vpc_id = aws_vpc.main.id
  tags   = { Name = "\${local.name_prefix}-vgw" }
}

resource "aws_vpn_gateway_attachment" "main" {
  vpc_id         = aws_vpc.main.id
  vpn_gateway_id = aws_vpn_gateway.main.id
}
`);
  }

  // ── Elastic IP ────────────────────────────────────────────────────────────
  if (has("elastic-ip") && !has("nat-gateway")) {
    lines.push(`# ── Elastic IP ${"─".repeat(49)}
resource "aws_eip" "main" {
  domain = "vpc"
  tags   = { Name = "\${local.name_prefix}-eip" }
}
`);
  }

  // ── Backup ────────────────────────────────────────────────────────────────
  if (has("backup")) {
    lines.push(`# ── AWS Backup ${"─".repeat(49)}
resource "aws_backup_vault" "main" {
  name = "\${local.name_prefix}-vault"
  tags = { Name = "\${local.name_prefix}-vault" }
}

resource "aws_backup_plan" "main" {
  name = "\${local.name_prefix}-backup-plan"
  rule {
    rule_name         = "daily-backup"
    target_vault_name = aws_backup_vault.main.name
    schedule          = "cron(0 2 * * ? *)"
    lifecycle { delete_after = 30 }
  }
  tags = { Name = "\${local.name_prefix}-backup-plan" }
}

resource "aws_iam_role" "backup" {
  name = "\${local.name_prefix}-backup-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole"; Effect = "Allow"; Principal = { Service = "backup.amazonaws.com" } }]
  })
}

resource "aws_iam_role_policy_attachment" "backup" {
  role       = aws_iam_role.backup.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"
}

resource "aws_backup_selection" "main" {
  name         = "\${local.name_prefix}-selection"
  plan_id      = aws_backup_plan.main.id
  iam_role_arn = aws_iam_role.backup.arn
  resources    = ["*"]
}
`);
  }

  // ── EBS Snapshot Lifecycle ────────────────────────────────────────────────
  if (has("snapshot")) {
    lines.push(`# ── EBS Snapshot Lifecycle ${"─".repeat(37)}
resource "aws_iam_role" "dlm" {
  name = "\${local.name_prefix}-dlm-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole"; Effect = "Allow"; Principal = { Service = "dlm.amazonaws.com" } }]
  })
}

resource "aws_iam_role_policy_attachment" "dlm" {
  role       = aws_iam_role.dlm.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSDataLifecycleManagerServiceRole"
}

resource "aws_dlm_lifecycle_policy" "ebs_snapshots" {
  description        = "Daily EBS snapshots — retain 7"
  execution_role_arn = aws_iam_role.dlm.arn
  state              = "ENABLED"

  policy_details {
    resource_types = ["VOLUME"]
    schedule {
      name = "Daily snapshots"
      create_rule { interval = 24; interval_unit = "HOURS"; times = ["02:00"] }
      retain_rule { count = 7 }
    }
    target_tags = { Backup = "true" }
  }
  tags = { Name = "\${local.name_prefix}-dlm" }
}
`);
  }

  // ── Outputs ───────────────────────────────────────────────────────────────
  lines.push(`# ── Outputs ${"─".repeat(52)}`);
  if (needsVpc) lines.push(`output "vpc_id"          { value = aws_vpc.main.id }`);
  if (has("control-plane") && needsVpc) lines.push(`output "eks_cluster_name" { value = aws_eks_cluster.main.name }
output "eks_endpoint"     { value = aws_eks_cluster.main.endpoint }`);
  if (has("app-load-balancer") && needsVpc) lines.push(`output "alb_dns_name"     { value = aws_lb.main.dns_name }`);
  if (has("managed-database") && needsVpc) lines.push(`output "db_endpoint"      { value = aws_db_instance.main.endpoint }`);
  if (has("object-storage")) lines.push(`output "s3_bucket_name"   { value = aws_s3_bucket.main.bucket }`);
  if (has("registry")) lines.push(`output "ecr_repo_url"     { value = aws_ecr_repository.main.repository_url }`);
  if (has("api-gateway")) lines.push(`output "api_endpoint"     { value = aws_apigatewayv2_stage.main.invoke_url }`);

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Azure
// ─────────────────────────────────────────────────────────────────────────────
function generateAzure(services: string[], region: string): string {
  const has = (id: string) => services.includes(id);
  const needsNet = services.some(s =>
    ["vpc","public-subnet","private-subnet","nat-gateway","route-table","nacl","security-group",
     "app-load-balancer","load-balancer","control-plane","vm-instance","serverless-compute",
     "functions","managed-database","cache","bastion-host","block-storage","file-storage",
     "vpn-gateway"].includes(s)
  );

  const lines: string[] = [];
  lines.push(header("Azure", region, services));

  lines.push(`terraform {
  required_version = ">= 1.6"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {
    resource_group { prevent_deletion_if_contains_resources = false }
    key_vault      { purge_soft_delete_on_destroy = true; recover_soft_deleted_key_vaults = true }
  }
}

# ── Variables ${"─".repeat(50)}
variable "location" {
  description = "Azure region"
  type        = string
  default     = "${region}"
}
variable "project_name" {
  type    = string
  default = "myapp"
}
variable "environment" {
  type    = string
  default = "prod"
}
${has("managed-database") ? `variable "db_admin_password" {
  type      = string
  sensitive = true
  default   = "ChangeMe123!"
}` : ""}

# ── Locals ${"─".repeat(53)}
locals {
  name_prefix = "\${var.project_name}-\${var.environment}"
  common_tags = { Project = var.project_name; Environment = var.environment; ManagedBy = "terraform" }
}

# ── Resource Group ${"─".repeat(46)}
resource "azurerm_resource_group" "main" {
  name     = "\${local.name_prefix}-rg"
  location = var.location
  tags     = local.common_tags
}
`);

  if (needsNet) {
    lines.push(`# ── Virtual Network ${"─".repeat(44)}
resource "azurerm_virtual_network" "main" {
  name                = "\${local.name_prefix}-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tags                = local.common_tags
}

resource "azurerm_subnet" "public" {
  name                 = "\${local.name_prefix}-public"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_subnet" "private" {
  name                 = "\${local.name_prefix}-private"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_subnet" "db" {
  name                 = "\${local.name_prefix}-db"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.3.0/24"]
  delegation {
    name = "flexserver"
    service_delegation { name = "Microsoft.DBforPostgreSQL/flexibleServers" }
  }
}
`);

    if (has("nat-gateway")) {
      lines.push(`resource "azurerm_public_ip" "nat" {
  name                = "\${local.name_prefix}-nat-pip"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_nat_gateway" "main" {
  name                    = "\${local.name_prefix}-nat"
  location                = azurerm_resource_group.main.location
  resource_group_name     = azurerm_resource_group.main.name
  sku_name                = "Standard"
  idle_timeout_in_minutes = 10
}

resource "azurerm_nat_gateway_public_ip_association" "main" {
  nat_gateway_id       = azurerm_nat_gateway.main.id
  public_ip_address_id = azurerm_public_ip.nat.id
}

resource "azurerm_subnet_nat_gateway_association" "private" {
  subnet_id      = azurerm_subnet.private.id
  nat_gateway_id = azurerm_nat_gateway.main.id
}
`);
    }

    if (has("nacl") || has("security-group")) {
      lines.push(`# ── Network Security Groups ${"─".repeat(37)}
resource "azurerm_network_security_group" "public" {
  name                = "\${local.name_prefix}-nsg-public"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  security_rule { name = "AllowHTTP";   priority = 100; direction = "Inbound"; access = "Allow"; protocol = "Tcp"; source_port_range = "*"; destination_port_range = "80";   source_address_prefix = "*"; destination_address_prefix = "*" }
  security_rule { name = "AllowHTTPS";  priority = 110; direction = "Inbound"; access = "Allow"; protocol = "Tcp"; source_port_range = "*"; destination_port_range = "443";  source_address_prefix = "*"; destination_address_prefix = "*" }
  security_rule { name = "DenyAllIn";   priority = 4096; direction = "Inbound"; access = "Deny"; protocol = "*";   source_port_range = "*"; destination_port_range = "*";    source_address_prefix = "*"; destination_address_prefix = "*" }
  tags = local.common_tags
}

resource "azurerm_subnet_network_security_group_association" "public" {
  subnet_id                 = azurerm_subnet.public.id
  network_security_group_id = azurerm_network_security_group.public.id
}

resource "azurerm_network_security_group" "private" {
  name                = "\${local.name_prefix}-nsg-private"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  security_rule { name = "AllowVNet"; priority = 100; direction = "Inbound"; access = "Allow"; protocol = "*"; source_port_range = "*"; destination_port_range = "*"; source_address_prefix = "VirtualNetwork"; destination_address_prefix = "VirtualNetwork" }
  tags = local.common_tags
}

resource "azurerm_subnet_network_security_group_association" "private" {
  subnet_id                 = azurerm_subnet.private.id
  network_security_group_id = azurerm_network_security_group.private.id
}
`);
    }
  }

  if (has("bastion-host")) {
    lines.push(`# ── Azure Bastion ${"─".repeat(46)}
resource "azurerm_subnet" "bastion" {
  name                 = "AzureBastionSubnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.4.0/26"]
}

resource "azurerm_public_ip" "bastion" {
  name                = "\${local.name_prefix}-bastion-pip"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_bastion_host" "main" {
  name                = "\${local.name_prefix}-bastion"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "Basic"
  ip_configuration { name = "config"; subnet_id = azurerm_subnet.bastion.id; public_ip_address_id = azurerm_public_ip.bastion.id }
  tags = local.common_tags
}
`);
  }

  if (has("acm")) {
    lines.push(`# ── Key Vault (TLS Certificates) ${"─".repeat(31)}
data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "certs" {
  name                     = "\${local.name_prefix}-kv-certs"
  location                 = azurerm_resource_group.main.location
  resource_group_name      = azurerm_resource_group.main.name
  tenant_id                = data.azurerm_client_config.current.tenant_id
  sku_name                 = "standard"
  purge_protection_enabled = true

  access_policy {
    tenant_id               = data.azurerm_client_config.current.tenant_id
    object_id               = data.azurerm_client_config.current.object_id
    certificate_permissions = ["Create","Get","List","Import","Delete","Purge"]
    key_permissions         = ["Get","List"]
    secret_permissions      = ["Get","List","Set","Delete","Purge"]
  }
  tags = local.common_tags
}
`);
  }

  if (has("app-load-balancer") && needsNet) {
    lines.push(`# ── Application Gateway ${"─".repeat(40)}
resource "azurerm_public_ip" "agw" {
  name                = "\${local.name_prefix}-agw-pip"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_subnet" "agw" {
  name                 = "\${local.name_prefix}-agw-subnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.5.0/24"]
}

resource "azurerm_application_gateway" "main" {
  name                = "\${local.name_prefix}-agw"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  sku                { name = "Standard_v2"; tier = "Standard_v2"; capacity = 1 }
  gateway_ip_configuration { name = "gw-ip-config"; subnet_id = azurerm_subnet.agw.id }
  frontend_port      { name = "http-80"; port = 80 }
  frontend_port      { name = "https-443"; port = 443 }
  frontend_ip_configuration { name = "frontend-ip"; public_ip_address_id = azurerm_public_ip.agw.id }

  backend_address_pool   { name = "backend-pool" }
  backend_http_settings  { name = "http-settings"; cookie_based_affinity = "Disabled"; port = 8080; protocol = "Http"; request_timeout = 60 }
  http_listener          { name = "http-listener"; frontend_ip_configuration_name = "frontend-ip"; frontend_port_name = "http-80"; protocol = "Http" }
  request_routing_rule   { name = "routing-rule"; rule_type = "Basic"; http_listener_name = "http-listener"; backend_address_pool_name = "backend-pool"; backend_http_settings_name = "http-settings"; priority = 100 }
  tags = local.common_tags
}
`);
  }

  if (has("control-plane")) {
    lines.push(`# ── AKS Kubernetes Cluster ${"─".repeat(37)}
resource "azurerm_kubernetes_cluster" "main" {
  name                = "\${local.name_prefix}-aks"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  dns_prefix          = "\${local.name_prefix}-aks"
  kubernetes_version  = "1.30"

  default_node_pool {
    name           = "default"
    node_count     = 2
    vm_size        = "Standard_D2_v2"
    ${needsNet ? `vnet_subnet_id = azurerm_subnet.private.id` : ""}
    os_disk_size_gb = 50
  }

  identity { type = "SystemAssigned" }

  network_profile {
    network_plugin    = "azure"
    load_balancer_sku = "standard"
  }

  tags = local.common_tags
}
`);
  }

  if (has("vm-instance") && !has("control-plane") && needsNet) {
    lines.push(`# ── Linux Virtual Machine ${"─".repeat(38)}
resource "azurerm_network_interface" "app" {
  name                = "\${local.name_prefix}-nic"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  ip_configuration { name = "internal"; subnet_id = azurerm_subnet.private.id; private_ip_address_allocation = "Dynamic" }
}

resource "azurerm_linux_virtual_machine" "app" {
  name                            = "\${local.name_prefix}-vm"
  location                        = azurerm_resource_group.main.location
  resource_group_name             = azurerm_resource_group.main.name
  size                            = "Standard_D2_v2"
  admin_username                  = "azureuser"
  disable_password_authentication = true
  network_interface_ids           = [azurerm_network_interface.app.id]

  admin_ssh_key { username = "azureuser"; public_key = file("~/.ssh/id_rsa.pub") }

  os_disk { caching = "ReadWrite"; storage_account_type = "Premium_LRS" }
  source_image_reference { publisher = "Canonical"; offer = "0001-com-ubuntu-server-jammy"; sku = "22_04-lts"; version = "latest" }
  tags = local.common_tags
}
`);
  }

  if (has("serverless-compute")) {
    lines.push(`# ── Azure Container Instance ${"─".repeat(35)}
resource "azurerm_container_group" "main" {
  name                = "\${local.name_prefix}-aci"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  ip_address_type     = "Public"
  os_type             = "Linux"
  restart_policy      = "Always"

  container {
    name   = "app"
    image  = "nginx:latest"
    cpu    = "1.0"
    memory = "1.5"
    ports  { port = 80; protocol = "TCP" }
  }
  tags = local.common_tags
}
`);
  }

  if (has("functions")) {
    lines.push(`# ── Azure Function App ${"─".repeat(42)}
resource "azurerm_storage_account" "func" {
  name                     = "\${replace(local.name_prefix, "-", "")}fnsa"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  tags                     = local.common_tags
}

resource "azurerm_service_plan" "func" {
  name                = "\${local.name_prefix}-fn-plan"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  os_type             = "Linux"
  sku_name            = "Y1"
}

resource "azurerm_linux_function_app" "main" {
  name                       = "\${local.name_prefix}-fn"
  location                   = azurerm_resource_group.main.location
  resource_group_name        = azurerm_resource_group.main.name
  service_plan_id            = azurerm_service_plan.func.id
  storage_account_name       = azurerm_storage_account.func.name
  storage_account_access_key = azurerm_storage_account.func.primary_access_key

  site_config {
    application_stack { node_version = "20" }
  }
  tags = local.common_tags
}
`);
  }

  if (has("registry")) {
    lines.push(`# ── Azure Container Registry ${"─".repeat(35)}
resource "azurerm_container_registry" "main" {
  name                = "\${replace(local.name_prefix, "-", "")}acr"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  sku                 = "Basic"
  admin_enabled       = true
  tags                = local.common_tags
}
`);
  }

  if (has("managed-database")) {
    lines.push(`# ── Azure Database for PostgreSQL ${"─".repeat(30)}
resource "azurerm_postgresql_flexible_server" "main" {
  name                   = "\${local.name_prefix}-postgres"
  location               = azurerm_resource_group.main.location
  resource_group_name    = azurerm_resource_group.main.name
  version                = "16"
  administrator_login    = "dbadmin"
  administrator_password = var.db_admin_password
  storage_mb             = 32768
  sku_name               = "GP_Standard_D2ds_v4"
  backup_retention_days  = 7
  geo_redundant_backup_enabled = true
  ${needsNet ? `delegated_subnet_id    = azurerm_subnet.db.id` : ""}
  zone                   = "1"
  tags                   = local.common_tags
}

resource "azurerm_postgresql_flexible_server_database" "app" {
  name      = "appdb"
  server_id = azurerm_postgresql_flexible_server.main.id
  collation = "en_US.utf8"
  charset   = "utf8"
}
`);
  }

  if (has("cache")) {
    lines.push(`# ── Azure Cache for Redis ${"─".repeat(38)}
resource "azurerm_redis_cache" "main" {
  name                = "\${local.name_prefix}-redis"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  capacity            = 1
  family              = "C"
  sku_name            = "Standard"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"
  tags                = local.common_tags
}
`);
  }

  if (has("object-storage")) {
    lines.push(`# ── Azure Blob Storage ${"─".repeat(42)}
resource "azurerm_storage_account" "main" {
  name                     = "\${replace(local.name_prefix, "-", "")}sa"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
  tags                     = local.common_tags
}

resource "azurerm_storage_container" "assets" {
  name                  = "assets"
  storage_account_name  = azurerm_storage_account.main.name
  container_access_type = "private"
}
`);
  }

  if (has("secrets-manager")) {
    lines.push(`# ── Azure Key Vault (Secrets) ${"─".repeat(34)}
${!has("acm") ? `data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "certs" {
  name                     = "\${local.name_prefix}-kv"
  location                 = azurerm_resource_group.main.location
  resource_group_name      = azurerm_resource_group.main.name
  tenant_id                = data.azurerm_client_config.current.tenant_id
  sku_name                 = "standard"
  purge_protection_enabled = true

  access_policy {
    tenant_id          = data.azurerm_client_config.current.tenant_id
    object_id          = data.azurerm_client_config.current.object_id
    secret_permissions = ["Get","List","Set","Delete","Purge"]
  }
  tags = local.common_tags
}` : ""}

resource "azurerm_key_vault_secret" "db_password" {
  name         = "db-password"
  value        = "REPLACE_ME"
  key_vault_id = azurerm_key_vault.certs.id
}
`);
  }

  if (has("monitoring-logging")) {
    lines.push(`# ── Log Analytics Workspace ${"─".repeat(36)}
resource "azurerm_log_analytics_workspace" "main" {
  name                = "\${local.name_prefix}-law"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = local.common_tags
}

resource "azurerm_monitor_metric_alert" "cpu_high" {
  name                = "\${local.name_prefix}-cpu-alert"
  resource_group_name = azurerm_resource_group.main.name
  scopes              = [azurerm_resource_group.main.id]
  description         = "CPU exceeded 80%"
  severity            = 2

  criteria {
    metric_namespace = "Microsoft.Compute/virtualMachines"
    metric_name      = "Percentage CPU"
    aggregation      = "Average"
    operator         = "GreaterThan"
    threshold        = 80
  }
  tags = local.common_tags
}
`);
  }

  if (has("message-queue")) {
    lines.push(`# ── Azure Service Bus ${"─".repeat(43)}
resource "azurerm_servicebus_namespace" "main" {
  name                = "\${local.name_prefix}-sb"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "Standard"
  tags                = local.common_tags
}

resource "azurerm_servicebus_queue" "main" {
  name         = "\${local.name_prefix}-queue"
  namespace_id = azurerm_servicebus_namespace.main.id
  enable_partitioning = true
}
`);
  }

  if (has("event-bus")) {
    lines.push(`# ── Azure Event Grid ${"─".repeat(43)}
resource "azurerm_eventgrid_topic" "main" {
  name                = "\${local.name_prefix}-events"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tags                = local.common_tags
}
`);
  }

  lines.push(`# ── Outputs ${"─".repeat(52)}`);
  if (needsNet) lines.push(`output "vnet_id"          { value = azurerm_virtual_network.main.id }`);
  if (has("control-plane")) lines.push(`output "aks_name"         { value = azurerm_kubernetes_cluster.main.name }
output "aks_host"         { value = azurerm_kubernetes_cluster.main.kube_config[0].host; sensitive = true }`);
  if (has("app-load-balancer") && needsNet) lines.push(`output "agw_public_ip"    { value = azurerm_public_ip.agw.ip_address }`);
  if (has("managed-database")) lines.push(`output "db_fqdn"          { value = azurerm_postgresql_flexible_server.main.fqdn }`);
  if (has("object-storage")) lines.push(`output "storage_account"  { value = azurerm_storage_account.main.name }`);
  if (has("registry")) lines.push(`output "acr_login_server" { value = azurerm_container_registry.main.login_server }`);

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// GCP
// ─────────────────────────────────────────────────────────────────────────────
function generateGcp(services: string[], region: string): string {
  const has = (id: string) => services.includes(id);
  const needsNet = services.some(s =>
    ["vpc","public-subnet","private-subnet","nat-gateway","route-table","nacl","security-group",
     "app-load-balancer","load-balancer","control-plane","vm-instance","serverless-compute",
     "managed-database","cache","bastion-host","block-storage","file-storage","vpn-gateway"].includes(s)
  );

  const lines: string[] = [];
  lines.push(header("GCP", region, services));

  lines.push(`terraform {
  required_version = ">= 1.6"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.gcp_region
}

# ── Variables ${"─".repeat(50)}
variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}
variable "gcp_region" {
  description = "GCP region"
  type        = string
  default     = "${region}"
}
variable "project_name" {
  type    = string
  default = "myapp"
}
variable "environment" {
  type    = string
  default = "prod"
}

# ── Locals ${"─".repeat(53)}
locals {
  name_prefix  = "\${var.project_name}-\${var.environment}"
  common_labels = { project = var.project_name; environment = var.environment; managed_by = "terraform" }
}
`);

  const apis = ["compute.googleapis.com"];
  if (has("control-plane")) apis.push("container.googleapis.com");
  if (has("functions")) apis.push("cloudfunctions.googleapis.com", "cloudbuild.googleapis.com");
  if (has("serverless-compute")) apis.push("run.googleapis.com");
  if (has("secrets-manager")) apis.push("secretmanager.googleapis.com");
  if (has("registry")) apis.push("artifactregistry.googleapis.com");
  if (has("managed-database")) apis.push("sqladmin.googleapis.com");
  if (has("waf")) apis.push("compute.googleapis.com");
  if (has("dns")) apis.push("dns.googleapis.com");
  if (has("api-gateway")) apis.push("apigateway.googleapis.com");
  if (has("event-bus")) apis.push("eventarc.googleapis.com");

  lines.push(`# ── Enable APIs ${"─".repeat(48)}
${[...new Set(apis)].map(api => `resource "google_project_service" "${api.replace(/\./g, "_").replace("googleapis_com", "api")}" {
  service            = "${api}"
  disable_on_destroy = false
}`).join("\n")}
`);

  if (needsNet) {
    lines.push(`# ── VPC Network & Subnets ${"─".repeat(38)}
resource "google_compute_network" "main" {
  name                    = "\${local.name_prefix}-vpc"
  auto_create_subnetworks = false
  project                 = var.project_id
}

resource "google_compute_subnetwork" "public" {
  name          = "\${local.name_prefix}-public"
  ip_cidr_range = "10.0.1.0/24"
  region        = var.gcp_region
  network       = google_compute_network.main.id
}

resource "google_compute_subnetwork" "private" {
  name                     = "\${local.name_prefix}-private"
  ip_cidr_range            = "10.0.2.0/24"
  region                   = var.gcp_region
  network                  = google_compute_network.main.id
  private_ip_google_access = true
}
`);

    if (has("nat-gateway") || has("internet-gateway")) {
      lines.push(`resource "google_compute_router" "main" {
  name    = "\${local.name_prefix}-router"
  region  = var.gcp_region
  network = google_compute_network.main.id
}

resource "google_compute_router_nat" "main" {
  name                               = "\${local.name_prefix}-nat"
  router                             = google_compute_router.main.name
  region                             = var.gcp_region
  nat_ip_allocate_option             = "AUTO_ONLY"
  source_subnetwork_ip_ranges_to_nat = "ALL_SUBNETWORKS_ALL_IP_RANGES"
}
`);
    }

    if (has("nacl") || has("security-group")) {
      lines.push(`# ── Firewall Rules ${"─".repeat(45)}
resource "google_compute_firewall" "allow_http_https" {
  name    = "\${local.name_prefix}-allow-web"
  network = google_compute_network.main.name

  allow { protocol = "tcp"; ports = ["80", "443"] }
  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["web"]
}

resource "google_compute_firewall" "allow_internal" {
  name    = "\${local.name_prefix}-allow-internal"
  network = google_compute_network.main.name

  allow { protocol = "tcp"; ports = ["0-65535"] }
  allow { protocol = "udp"; ports = ["0-65535"] }
  allow { protocol = "icmp" }
  source_ranges = ["10.0.0.0/16"]
}

resource "google_compute_firewall" "allow_iap_ssh" {
  name    = "\${local.name_prefix}-allow-iap"
  network = google_compute_network.main.name

  allow { protocol = "tcp"; ports = ["22"] }
  source_ranges = ["35.235.240.0/20"]
  target_tags   = ["bastion", "ssh"]
}
`);
    }
  }

  if (has("bastion-host") && needsNet) {
    lines.push(`# ── Bastion VM (with IAP) ${"─".repeat(38)}
resource "google_compute_instance" "bastion" {
  name         = "\${local.name_prefix}-bastion"
  machine_type = "f1-micro"
  zone         = "\${var.gcp_region}-a"

  boot_disk {
    initialize_params { image = "debian-cloud/debian-12" }
  }

  network_interface {
    network    = google_compute_network.main.name
    subnetwork = google_compute_subnetwork.public.name
  }

  tags   = ["bastion", "ssh"]
  labels = local.common_labels
}
`);
  }

  if (has("acm")) {
    lines.push(`# ── Managed SSL Certificate ${"─".repeat(36)}
resource "google_compute_managed_ssl_certificate" "main" {
  name = "\${local.name_prefix}-ssl"
  managed { domains = ["example.com", "www.example.com"] }
}
`);
  }

  if (has("app-load-balancer") && needsNet) {
    lines.push(`# ── HTTP(S) Load Balancer ${"─".repeat(38)}
resource "google_compute_global_address" "lb" {
  name = "\${local.name_prefix}-lb-ip"
}

resource "google_compute_backend_service" "main" {
  name                  = "\${local.name_prefix}-backend"
  protocol              = "HTTP"
  load_balancing_scheme = "EXTERNAL_MANAGED"
  health_checks         = [google_compute_http_health_check.main.id]
}

resource "google_compute_http_health_check" "main" {
  name               = "\${local.name_prefix}-health"
  request_path       = "/health"
  check_interval_sec = 10
}

resource "google_compute_url_map" "main" {
  name            = "\${local.name_prefix}-urlmap"
  default_service = google_compute_backend_service.main.id
}

resource "google_compute_target_https_proxy" "main" {
  name             = "\${local.name_prefix}-https-proxy"
  url_map          = google_compute_url_map.main.id
  ssl_certificates = ${has("acm") ? "[google_compute_managed_ssl_certificate.main.id]" : "[]"}
}

resource "google_compute_global_forwarding_rule" "https" {
  name                  = "\${local.name_prefix}-https"
  ip_address            = google_compute_global_address.lb.address
  port_range            = "443"
  target                = google_compute_target_https_proxy.main.id
  load_balancing_scheme = "EXTERNAL_MANAGED"
}
`);
  }

  if (has("control-plane") && needsNet) {
    lines.push(`# ── GKE Cluster ${"─".repeat(48)}
resource "google_container_cluster" "main" {
  name                     = "\${local.name_prefix}-gke"
  location                 = var.gcp_region
  remove_default_node_pool = true
  initial_node_count       = 1
  network                  = google_compute_network.main.name
  subnetwork               = google_compute_subnetwork.private.name

  private_cluster_config {
    enable_private_nodes    = true
    enable_private_endpoint = false
    master_ipv4_cidr_block  = "172.16.0.0/28"
  }

  ip_allocation_policy {}
  release_channel { channel = "REGULAR" }
}

resource "google_container_node_pool" "main" {
  name       = "\${local.name_prefix}-nodes"
  cluster    = google_container_cluster.main.id
  location   = var.gcp_region
  node_count = 2

  node_config {
    machine_type = "e2-medium"
    disk_size_gb = 50
    disk_type    = "pd-standard"
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform",
    ]
    labels = local.common_labels
    tags   = ["gke-node"]
  }

  autoscaling { min_node_count = 1; max_node_count = 5 }
  management  { auto_repair = true; auto_upgrade = true }
}
`);
  } else if (has("vm-instance") && needsNet) {
    lines.push(`# ── Compute Engine VM ${"─".repeat(42)}
resource "google_compute_instance" "app" {
  name         = "\${local.name_prefix}-vm"
  machine_type = "e2-medium"
  zone         = "\${var.gcp_region}-a"

  boot_disk {
    initialize_params { image = "debian-cloud/debian-12"; size = 50; type = "pd-ssd" }
  }

  network_interface {
    network    = google_compute_network.main.name
    subnetwork = google_compute_subnetwork.private.name
  }

  tags   = ["app"]
  labels = local.common_labels
}
`);
  }

  if (has("serverless-compute")) {
    lines.push(`# ── Cloud Run ${"─".repeat(50)}
resource "google_cloud_run_v2_service" "main" {
  name     = "\${local.name_prefix}-run"
  location = var.gcp_region

  template {
    containers {
      image = "nginx:latest"
      resources { limits = { cpu = "1"; memory = "512Mi" } }
      ports { container_port = 8080 }
    }
    scaling { max_instance_count = 10; min_instance_count = 0 }
  }

  labels = local.common_labels
}

resource "google_cloud_run_v2_service_iam_member" "public" {
  project  = var.project_id
  location = var.gcp_region
  name     = google_cloud_run_v2_service.main.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}
`);
  }

  if (has("functions")) {
    lines.push(`# ── Cloud Functions (Gen 2) ${"─".repeat(36)}
resource "google_storage_bucket" "fn_source" {
  name                        = "\${local.name_prefix}-fn-source-\${var.project_id}"
  location                    = var.gcp_region
  uniform_bucket_level_access = true
}

resource "google_cloudfunctions2_function" "main" {
  name     = "\${local.name_prefix}-fn"
  location = var.gcp_region

  build_config {
    runtime     = "nodejs20"
    entry_point = "handler"
    source { storage_source { bucket = google_storage_bucket.fn_source.name; object = "function-source.zip" } }
  }

  service_config {
    available_memory      = "512M"
    timeout_seconds       = 60
    max_instance_count    = 10
    min_instance_count    = 0
  }

  labels = local.common_labels
}
`);
  }

  if (has("registry")) {
    lines.push(`# ── Artifact Registry ${"─".repeat(42)}
resource "google_artifact_registry_repository" "main" {
  location      = var.gcp_region
  repository_id = "\${local.name_prefix}-repo"
  description   = "Docker container images"
  format        = "DOCKER"
  labels        = local.common_labels
}
`);
  }

  if (has("managed-database")) {
    lines.push(`# ── Cloud SQL PostgreSQL ${"─".repeat(39)}
resource "google_sql_database_instance" "main" {
  name             = "\${local.name_prefix}-postgres"
  database_version = "POSTGRES_16"
  region           = var.gcp_region

  settings {
    tier              = "db-custom-2-4096"
    availability_type = "REGIONAL"
    disk_autoresize   = true
    disk_size         = 20
    disk_type         = "PD_SSD"

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      start_time                     = "02:00"
      backup_retention_settings { retained_backups = 7 }
    }

    ip_configuration {
      ipv4_enabled    = false
      ${needsNet ? `private_network  = google_compute_network.main.id` : `ipv4_enabled = true`}
    }
  }

  deletion_protection = true
}

resource "google_sql_database" "app" {
  name     = "appdb"
  instance = google_sql_database_instance.main.name
}

resource "google_sql_user" "app" {
  name     = "dbadmin"
  instance = google_sql_database_instance.main.name
  password = "REPLACE_ME"
}
`);
  }

  if (has("cache")) {
    lines.push(`# ── Cloud Memorystore (Redis) ${"─".repeat(34)}
resource "google_redis_instance" "main" {
  name               = "\${local.name_prefix}-redis"
  tier               = "BASIC"
  memory_size_gb     = 1
  region             = var.gcp_region
  redis_version      = "REDIS_7_0"
  ${needsNet ? `authorized_network = google_compute_network.main.id` : ""}
  labels             = local.common_labels
}
`);
  }

  if (has("object-storage")) {
    lines.push(`# ── Cloud Storage ${"─".repeat(46)}
resource "google_storage_bucket" "main" {
  name                        = "\${local.name_prefix}-assets-\${var.project_id}"
  location                    = upper(var.gcp_region)
  storage_class               = "STANDARD"
  uniform_bucket_level_access = true
  force_destroy               = false

  versioning { enabled = true }

  lifecycle_rule {
    action { type = "SetStorageClass"; storage_class = "NEARLINE" }
    condition { age = 90 }
  }
}
`);
  }

  if (has("secrets-manager")) {
    lines.push(`# ── Secret Manager ${"─".repeat(45)}
resource "google_secret_manager_secret" "app" {
  secret_id = "\${local.name_prefix}-secrets"
  replication { auto {} }
  labels = local.common_labels
}

resource "google_secret_manager_secret_version" "app" {
  secret      = google_secret_manager_secret.app.id
  secret_data = jsonencode({ DB_PASSWORD = "REPLACE_ME"; API_KEY = "REPLACE_ME" })
}
`);
  }

  if (has("monitoring-logging")) {
    lines.push(`# ── Cloud Monitoring & Logging ${"─".repeat(33)}
resource "google_monitoring_alert_policy" "cpu_high" {
  display_name = "\${local.name_prefix}-cpu-high"
  combiner     = "OR"

  conditions {
    display_name = "CPU > 80%"
    condition_threshold {
      filter          = "resource.type = \\"gce_instance\\" AND metric.type = \\"compute.googleapis.com/instance/cpu/utilization\\""
      duration        = "60s"
      comparison      = "COMPARISON_GT"
      threshold_value = 0.8
      aggregations { alignment_period = "60s"; per_series_aligner = "ALIGN_MEAN" }
    }
  }

  notification_channels = []
  user_labels           = local.common_labels
}

resource "google_logging_metric" "error_count" {
  name   = "\${local.name_prefix}-error-count"
  filter = "severity >= ERROR"
  metric_descriptor {
    metric_kind = "DELTA"
    value_type  = "INT64"
    unit        = "1"
  }
}
`);
  }

  if (has("dns")) {
    lines.push(`# ── Cloud DNS ${"─".repeat(50)}
resource "google_dns_managed_zone" "main" {
  name     = "\${local.name_prefix}-zone"
  dns_name = "example.com."
  labels   = local.common_labels
}
`);
  }

  if (has("waf")) {
    lines.push(`# ── Cloud Armor (WAF) ${"─".repeat(42)}
resource "google_compute_security_policy" "main" {
  name = "\${local.name_prefix}-armor"

  rule {
    action      = "throttle"
    priority    = 100
    description = "Rate limit"
    match {
      versioned_expr = "SRC_IPS_V1"
      config { src_ip_ranges = ["0.0.0.0/0"] }
    }
    rate_limit_options {
      rate_limit_threshold { count = 1000; interval_sec = 60 }
      conform_action = "allow"
      exceed_action  = "deny(429)"
      enforce_on_key = "IP"
    }
  }

  rule {
    action      = "deny(403)"
    priority    = 200
    description = "Block XSS"
    match {
      expr { expression = "evaluatePreconfiguredExpr('xss-v33-stable')" }
    }
  }

  rule {
    action   = "allow"
    priority = 2147483647
    match {
      versioned_expr = "SRC_IPS_V1"
      config { src_ip_ranges = ["0.0.0.0/0"] }
    }
    description = "Default allow"
  }
}
`);
  }

  if (has("message-queue")) {
    lines.push(`# ── Cloud Pub/Sub ${"─".repeat(46)}
resource "google_pubsub_topic" "main" {
  name   = "\${local.name_prefix}-topic"
  labels = local.common_labels
}

resource "google_pubsub_subscription" "main" {
  name  = "\${local.name_prefix}-sub"
  topic = google_pubsub_topic.main.name

  ack_deadline_seconds       = 30
  message_retention_duration = "86400s"
  expiration_policy          { ttl = "" }
  retry_policy               { minimum_backoff = "10s"; maximum_backoff = "600s" }
}
`);
  }

  if (has("api-gateway")) {
    lines.push(`# ── API Gateway ${"─".repeat(48)}
resource "google_api_gateway_api" "main" {
  provider = google
  api_id   = "\${local.name_prefix}-api"
}

resource "google_api_gateway_api_config" "main" {
  provider      = google
  api           = google_api_gateway_api.main.api_id
  api_config_id = "\${local.name_prefix}-config"

  openapi_documents {
    document {
      path     = "spec.yaml"
      contents = base64encode(<<-YAML
        swagger: "2.0"
        info: { title: "API", version: "1.0" }
        paths:
          /hello:
            get:
              operationId: hello
              responses: { "200": { description: "OK" } }
        YAML
      )
    }
  }
  lifecycle { create_before_destroy = true }
}

resource "google_api_gateway_gateway" "main" {
  provider   = google
  api_config = google_api_gateway_api_config.main.id
  gateway_id = "\${local.name_prefix}-gw"
  region     = var.gcp_region
}
`);
  }

  if (has("elastic-ip")) {
    lines.push(`# ── External Static IP ${"─".repeat(41)}
resource "google_compute_address" "main" {
  name   = "\${local.name_prefix}-ip"
  region = var.gcp_region
}
`);
  }

  if (has("vpn-gateway") && needsNet) {
    lines.push(`# ── HA VPN Gateway ${"─".repeat(45)}
resource "google_compute_ha_vpn_gateway" "main" {
  name    = "\${local.name_prefix}-vpn"
  network = google_compute_network.main.id
  region  = var.gcp_region
}

resource "google_compute_external_vpn_gateway" "peer" {
  name            = "\${local.name_prefix}-peer-vpn"
  redundancy_type = "SINGLE_IP_INTERNALLY_REDUNDANT"
  interface { id = 0; ip_address = "203.0.113.1" } # Replace with peer gateway IP
}
`);
  }

  lines.push(`# ── Outputs ${"─".repeat(52)}`);
  if (needsNet) lines.push(`output "vpc_name"         { value = google_compute_network.main.name }`);
  if (has("control-plane") && needsNet) lines.push(`output "gke_cluster_name" { value = google_container_cluster.main.name }
output "gke_endpoint"     { value = google_container_cluster.main.endpoint; sensitive = true }`);
  if (has("app-load-balancer") && needsNet) lines.push(`output "lb_ip"            { value = google_compute_global_address.lb.address }`);
  if (has("managed-database")) lines.push(`output "db_connection"    { value = google_sql_database_instance.main.connection_name }`);
  if (has("object-storage")) lines.push(`output "gcs_bucket"       { value = google_storage_bucket.main.name }`);
  if (has("registry")) lines.push(`output "registry_url"     { value = "\${var.gcp_region}-docker.pkg.dev/\${var.project_id}/\${google_artifact_registry_repository.main.repository_id}" }`);

  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// Public entry point — single combined file
// ─────────────────────────────────────────────────────────────────────────────
export function generateTerraform(
  cloud: TfCloud,
  services: string[],
  region: string
): string {
  switch (cloud) {
    case "eks": return generateAws(services, region);
    case "aks": return generateAzure(services, region);
    case "gke": return generateGcp(services, region);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Multi-file split — returns Record<filename, content>
// ─────────────────────────────────────────────────────────────────────────────

const SECTION_FILE_MAP: [RegExp, string][] = [
  // terraform + provider stay in main.tf — handled separately
  [/Variables/i,                            "variables.tf"],
  [/Locals/i,                               "locals.tf"],
  [/Data Sources|Enable APIs/i,             "main.tf"],
  // Networking
  [/VPC|VNet|Virtual Network|Subnet|Route|NAT|NACL|Internet Gateway|Network ACL|Elastic IP|VPN|External Static/i, "networking.tf"],
  // Compute
  [/EKS Cluster|AKS Kubernetes|GKE Cluster|EC2 Instance|Linux Virtual Machine|Compute Engine VM|Fargate|Cloud Run|Cloud Function|Lambda|Container Instance|Container Registry|ECR|Artifact Registry|Bastion Host|Bastion VM/i, "compute.tf"],
  // Database
  [/RDS|PostgreSQL|MySQL|ElastiCache|Redis|Cloud SQL|Memorystore|Database for/i, "database.tf"],
  // Storage
  [/EBS|EFS|S3 Object|Blob Storage|Cloud Storage|Block Storage|File Storage|Managed Disk|Filestore|Snapshot Lifecycle|Snapshot/i, "storage.tf"],
  // Security
  [/Security Group|NSG|Network Security|WAF|ACM TLS|Key Vault|Secrets Manager|Secret Manager|Cloud Armor|SSL Certificate|Bastion/i, "security.tf"],
  // Load Balancers
  [/Load Balancer|Application Gateway|CloudFront|HTTP\(S\) Load|CDN/i, "loadbalancer.tf"],
  // Monitoring
  [/CloudWatch|Log Analytics|Monitoring|Logging/i, "monitoring.tf"],
  // DNS
  [/DNS|Route 53|Cloud DNS/i, "dns.tf"],
  // Messaging
  [/SQS|EventBridge|Service Bus|Event Grid|Pub\/Sub|Eventarc|API Gateway/i, "messaging.tf"],
  // Backup
  [/Backup|DLM|Snapshot/i, "backup.tf"],
  // Outputs
  [/Outputs/i, "outputs.tf"],
];

function classifySection(title: string): string {
  for (const [pattern, file] of SECTION_FILE_MAP) {
    if (pattern.test(title)) return file;
  }
  return "main.tf";
}

const FILE_ORDER = [
  "main.tf", "variables.tf", "locals.tf",
  "networking.tf", "compute.tf", "database.tf", "storage.tf",
  "security.tf", "loadbalancer.tf", "monitoring.tf",
  "dns.tf", "messaging.tf", "backup.tf", "outputs.tf",
];

const FILE_DESC: Record<string, string> = {
  "main.tf":          "Terraform & provider configuration",
  "variables.tf":     "Input variable declarations",
  "locals.tf":        "Local value computations",
  "networking.tf":    "VPC, subnets, IGW, NAT, route tables",
  "compute.tf":       "Kubernetes, VMs, containers, functions",
  "database.tf":      "Relational databases and cache clusters",
  "storage.tf":       "Block, file, object storage and registries",
  "security.tf":      "Security groups, WAF, secrets, certificates",
  "loadbalancer.tf":  "Load balancers and CDN distribution",
  "monitoring.tf":    "Logs, metrics and alert policies",
  "dns.tf":           "DNS hosted zones and record sets",
  "messaging.tf":     "Queues, event bus and API gateway",
  "backup.tf":        "Backup plans and snapshot schedules",
  "outputs.tf":       "Exported resource attributes",
};

export function generateTerraformFiles(
  cloud: TfCloud,
  services: string[],
  region: string
): Record<string, string> {
  const full = generateTerraform(cloud, services, region);
  const cloudName = cloud === "eks" ? "AWS" : cloud === "aks" ? "Azure" : "GCP";

  // Split on section comment boundaries
  const rawSections = full.split(/(?=\n# ── )/);

  const buckets: Record<string, string[]> = {};
  FILE_ORDER.forEach(f => { buckets[f] = []; });

  for (const section of rawSections) {
    const titleMatch = section.match(/# ── ([^─\n]+?) ─+/);
    const title = titleMatch ? titleMatch[1].trim() : "";

    // First chunk (file header + terraform + provider) goes to main.tf
    let file: string;
    if (!title || title.includes("Generated by TechAtlas") || title.includes("terraform") || title.includes("provider")) {
      file = "main.tf";
    } else {
      file = classifySection(title);
    }

    buckets[file].push(section.trimStart());
  }

  const result: Record<string, string> = {};
  for (const filename of FILE_ORDER) {
    const parts = buckets[filename].filter(p => p.trim().length > 0);
    if (parts.length === 0) continue;

    const desc = FILE_DESC[filename] ?? "";
    const fileHeader = [
      `# ${"═".repeat(60)}`,
      `# ${filename}`,
      `# ${desc}`,
      `# Cloud: ${cloudName} | Region: ${region} | Generated: ${TODAY}`,
      `# ${"═".repeat(60)}`,
      "",
    ].join("\n");

    result[filename] = fileHeader + parts.join("\n");
  }

  return result;
}
