// ozClient.ts
// -----------
// Thin client for the Oz control-plane API. Backs the merged product's shared
// authentication (a single Oz JWT works across the Oz dashboard at `/` and the
// InfraStudio SPA at `/studio/`) and the Design -> Deploy bridge that hands a
// generated IaC artifact to an Oz agent for provisioning.
import { OZ_API_BASE } from '../config/api';

const TOKEN_KEY = 'oz_token';

export function getToken(): string | null {
  return localStorage.getItem(TOKEN_KEY);
}

export function setToken(token: string): void {
  localStorage.setItem(TOKEN_KEY, token);
}

export function clearToken(): void {
  localStorage.removeItem(TOKEN_KEY);
}

export function isAuthenticated(): boolean {
  return !!getToken();
}

export interface OzUser {
  id: number;
  email: string;
  full_name: string;
}

/** Authenticate against Oz's OAuth2 password endpoint (form-encoded). */
export async function ozLogin(email: string, password: string): Promise<void> {
  const body = new URLSearchParams({ username: email, password });
  const res = await fetch(`${OZ_API_BASE}/auth/token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body,
  });
  if (!res.ok) {
    const detail = await res.json().catch(() => ({}));
    throw new Error((detail as { detail?: string }).detail || 'Invalid credentials');
  }
  const data = await res.json();
  if (!data.access_token) throw new Error('No token returned by Oz');
  setToken(data.access_token);
}

/** Reset password for an existing account by email (no email token required for internal use). */
export async function ozResetPassword(email: string, newPassword: string): Promise<void> {
  const res = await fetch(`${OZ_API_BASE}/auth/reset-password`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, new_password: newPassword }),
  });
  if (!res.ok) {
    const detail = await res.json().catch(() => ({}));
    throw new Error((detail as { detail?: string }).detail || 'Password reset failed');
  }
}

/** Create an Oz account, then log in with the same credentials. */
export async function ozRegister(email: string, password: string, fullName: string): Promise<void> {
  const res = await fetch(`${OZ_API_BASE}/auth/register`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password, full_name: fullName }),
  });
  if (!res.ok) {
    const detail = await res.json().catch(() => ({}));
    throw new Error((detail as { detail?: string }).detail || 'Registration failed');
  }
  await ozLogin(email, password);
}

export interface DeployResult {
  id: number;
  agent_type: string;
  status: string;
  message: string;
}

export interface DeployOptions {
  /** Human-readable name for the design being deployed. */
  name: string;
  /** The generated IaC source (Terraform / Ansible / Crossplane). */
  iac: string;
  /** Which generator produced it — used to phrase the agent instructions. */
  iacType?: 'terraform' | 'ansible' | 'crossplane' | string;
  /** Oz agent runtime to launch. Defaults to the free OpenCode runtime. */
  agentType?: string;
  /** Optional Oz server id to target (injects that server's credentials). */
  serverId?: number;
}

/**
 * Hand a generated IaC artifact to an Oz agent. The agent receives the IaC in
 * its prompt and is instructed to write it to disk, validate, and plan/apply it
 * (apply gated on its own confirmation rules). Requires a logged-in Oz session.
 */
export async function deployToOz(opts: DeployOptions): Promise<DeployResult> {
  const token = getToken();
  if (!token) throw new Error('Not authenticated with Oz — please sign in again.');

  const kind = opts.iacType || 'terraform';
  const prompt = [
    `You are deploying an infrastructure design named "${opts.name}" generated by InfraStudio.`,
    `The artifact is ${kind} code. Write it to a file in the working directory,`,
    `run the appropriate validate/plan step, summarise the planned changes, and apply`,
    `only if the plan is safe and complete.`,
    '',
    `\`\`\`${kind}`,
    opts.iac,
    '```',
  ].join('\n');

  const res = await fetch(`${OZ_API_BASE}/agents/launch`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      agent_type: opts.agentType || 'opencode',
      prompt,
      server_id: opts.serverId ?? null,
      max_runtime: 1800,
    }),
  });

  if (res.status === 401) {
    clearToken();
    throw new Error('Oz session expired — please sign in again.');
  }
  if (!res.ok) {
    const detail = await res.json().catch(() => ({}));
    throw new Error((detail as { detail?: string }).detail || `Deploy failed (${res.status})`);
  }
  return res.json();
}

// ───────────────────────────────────────────────────────────────────────────
// Generic authenticated request helper for the Oz control-plane API.
// ───────────────────────────────────────────────────────────────────────────
async function ozFetch<T = unknown>(path: string, opts: RequestInit = {}): Promise<T> {
  const token = getToken();
  if (!token) throw new Error('Not authenticated with Oz — please sign in again.');
  const res = await fetch(`${OZ_API_BASE}${path}`, {
    ...opts,
    headers: {
      Accept: 'application/json',
      ...(opts.body ? { 'Content-Type': 'application/json' } : {}),
      ...(opts.headers || {}),
      Authorization: `Bearer ${token}`,
    },
  });
  if (res.status === 401) {
    clearToken();
    throw new Error('Oz session expired — please sign in again.');
  }
  if (!res.ok) {
    const detail = await res.json().catch(() => ({}));
    throw new Error((detail as { detail?: string }).detail || `${opts.method || 'GET'} ${path} failed (${res.status})`);
  }
  if (res.status === 204) return undefined as T;
  return res.json() as Promise<T>;
}

// ── Dashboard ──────────────────────────────────────────────────────────────
export interface DashboardStats { total: number; running: number; completed: number; failed: number; }
export const getDashboardStats = () => ozFetch<DashboardStats>('/dashboard/stats');

// ── Agents ─────────────────────────────────────────────────────────────────
export type AgentStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'paused';

export interface AgentSummary {
  id: number;
  agent_type: string;
  status: AgentStatus;
  started_at: string | null;
  finished_at: string | null;
  created_at: string;
  exit_code: number | null;
}
export interface AgentDetail extends AgentSummary {
  prompt: string | null;
  container_id: string | null;
  error: string | null;
}
export interface AgentLogLine { stream: string; content: string; timestamp: string; }

export const AGENT_TYPES = [
  'opencode', 'claude-code', 'codex', 'gemini-cli', 'commandcode',
  'oz-local', 'github', 'custom',
  'cloudflare_docker_agent', 'cloudflare_server_health_agent', 'cloudflare_proxmox_agent',
] as const;

export interface LaunchAgentBody {
  agent_type: string;
  prompt?: string;
  server_id?: number | null;
  skill_id?: number | null;
  target_repos?: string[];
  env_vars?: Record<string, string>;
  max_runtime?: number;
}

export const listAgents = (status?: string, limit = 50) =>
  ozFetch<AgentSummary[]>(`/agents?limit=${limit}${status ? `&status=${encodeURIComponent(status)}` : ''}`);
export const getAgent = (id: number) => ozFetch<AgentDetail>(`/agents/${id}`);
export const launchAgent = (body: LaunchAgentBody) =>
  ozFetch<{ id: number; agent_type: string; status: string; message: string }>('/agents/launch', {
    method: 'POST', body: JSON.stringify(body),
  });
export const cancelAgent = (id: number) => ozFetch(`/agents/${id}/cancel`, { method: 'POST' });
export const retryAgent = (id: number) => ozFetch(`/agents/${id}/retry`, { method: 'POST' });
export const getAgentLogs = (id: number) => ozFetch<AgentLogLine[]>(`/agents/${id}/logs`);

// ── Servers ────────────────────────────────────────────────────────────────
export interface Server {
  id: number;
  name: string;
  host: string;
  port: number;
  username: string;
  auth_type: string;
  ssh_key_secret_id: number | null;
  ssh_password_secret_id: number | null;
  tags: string[];
  description: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export interface ServerCreateBody {
  name: string; host: string; port?: number; username: string;
  auth_type: string;
  ssh_key_secret_id?: number | null;
  ssh_password_secret_id?: number | null;
  tags?: string[]; description?: string | null;
}
export const listServers = () => ozFetch<Server[]>('/servers');
export const createServer = (body: ServerCreateBody) =>
  ozFetch<Server>('/servers', { method: 'POST', body: JSON.stringify(body) });
export const deleteServer = (id: number) => ozFetch<{ message: string }>(`/servers/${id}`, { method: 'DELETE' });

// ── Secrets ────────────────────────────────────────────────────────────────
export interface Secret { id: number; name: string; scope: string; created_at: string | null; }
export interface SecretCreateBody { name: string; value: string; scope?: string; }
export const listSecrets = () => ozFetch<Secret[]>('/secrets');
export const createSecret = (body: SecretCreateBody) =>
  ozFetch<{ id: number; name: string; scope: string }>('/secrets', { method: 'POST', body: JSON.stringify(body) });
export const deleteSecret = (id: number) => ozFetch<{ message: string }>(`/secrets/${id}`, { method: 'DELETE' });

// ── Schedules ──────────────────────────────────────────────────────────────
export interface Schedule {
  id: number; name: string; cron_expr: string; agent_type: string;
  is_active: boolean; last_run_at: string | null; created_at: string;
}
export interface ScheduleCreateBody {
  name: string; cron_expr: string; agent_type: string;
  skill_id?: number | null; prompt_template?: string | null; target_repos?: string[];
}
export const listSchedules = () => ozFetch<Schedule[]>('/schedules');
export const createSchedule = (body: ScheduleCreateBody) =>
  ozFetch<{ id: number; name: string; cron_expr: string }>('/schedules', { method: 'POST', body: JSON.stringify(body) });
export const toggleSchedule = (id: number, active: boolean) =>
  ozFetch<{ message: string; active: boolean }>(`/schedules/${id}/toggle?active=${active}`, { method: 'POST' });
